function deferred_dataref(name,type,notifier)
	print("Deffered dataref: "..name)
	dref=XLuaCreateDataRef(name, type,"yes",notifier)
	return wrap_dref_any(dref,type) 
end

simDR_fire_main_switch = find_dataref("tu154b2/custom/switchers/eng/fire_main_switch")
simDR_fire_place = find_dataref("tu154b2/custom/switchers/eng/fire_place_sel")
simDR_bus27_volt = find_dataref("tu154b2/custom/elec/bus27_volt_right")
azs_fireext1 = find_dataref("sim/custom/b2/azs_fireext1")
azs_fireext2 = find_dataref("sim/custom/b2/azs_fireext2")
simDR_passed = find_dataref("tu154b2/custom/time/frame_time")


-- lights list

simDR_light_fuel_pump_1 = find_dataref("tu154b2/custom/lights/small/fuel_pump_1")
simDR_light_fuel_pump_2 = find_dataref("tu154b2/custom/lights/small/fuel_pump_2")
simDR_light_fuel_pump_3 = find_dataref("tu154b2/custom/lights/small/fuel_pump_3")
simDR_light_fuel_pump_4 = find_dataref("tu154b2/custom/lights/small/fuel_pump_4")
simDR_light_fuel_pump_10 = find_dataref("tu154b2/custom/lights/small/fuel_pump_10")
simDR_light_fuel_pump_11 = find_dataref("tu154b2/custom/lights/small/fuel_pump_11")
simDR_light_fuel_pump_left_5 = find_dataref("tu154b2/custom/lights/small/fuel_pump_left_5")
simDR_light_fuel_pump_left_6 = find_dataref("tu154b2/custom/lights/small/fuel_pump_left_6")
simDR_light_fuel_pump_left_7 = find_dataref("tu154b2/custom/lights/small/fuel_pump_left_7")
simDR_light_fuel_pump_left_8 = find_dataref("tu154b2/custom/lights/small/fuel_pump_left_8")
simDR_light_fuel_pump_left_9 = find_dataref("tu154b2/custom/lights/small/fuel_pump_left_9")
simDR_light_fuel_pump_right_5 = find_dataref("tu154b2/custom/lights/small/fuel_pump_right_5")
simDR_light_fuel_pump_right_6 = find_dataref("tu154b2/custom/lights/small/fuel_pump_right_6")
simDR_light_fuel_pump_right_7 = find_dataref("tu154b2/custom/lights/small/fuel_pump_right_7")
simDR_light_fuel_pump_right_8 = find_dataref("tu154b2/custom/lights/small/fuel_pump_right_8")
simDR_light_fuel_pump_right_9 = find_dataref("tu154b2/custom/lights/small/fuel_pump_right_9")
simDR_light_fuel_pump_left_2_fail = find_dataref("tu154b2/custom/lights/small/fuel_tank2_left_fail")
simDR_light_fuel_pump_right_2_fail = find_dataref("tu154b2/custom/lights/small/fuel_tank2_right_fail")
simDR_light_fuel_pump_left_3_fail = find_dataref("tu154b2/custom/lights/small/fuel_tank3_left_fail")
simDR_light_fuel_pump_right_3_fail = find_dataref("tu154b2/custom/lights/small/fuel_tank3_right_fail")



simDR_pta6_fail = find_dataref("tu154b2/custom/lights/apu/pta6_fail")
simDR_start_apu = find_dataref("tu154b2/custom/lights/apu/start_apu")
simDR_high_rpm = find_dataref("tu154b2/custom/lights/apu/high_rpm")
simDR_high_temp = find_dataref("tu154b2/custom/lights/apu/high_temp")
simDR_start_ready = find_dataref("tu154b2/custom/lights/apu/start_ready")
simDR_work_mode = find_dataref("tu154b2/custom/lights/apu/work_mode")
simDR_low_oil_press = find_dataref("tu154b2/custom/lights/apu/low_oil_press")
simDR_fuel_press = find_dataref("tu154b2/custom/lights/apu/fuel_press")
simDR_low_oil = find_dataref("tu154b2/custom/lights/apu/low_oil")
simDR_doors_open = find_dataref("tu154b2/custom/lights/apu/doors_open")
simDR_eng1_reverse_lock = find_dataref("tu154b2/custom/lights/engines/eng1_reverse_lock")
simDR_eng1_reverse_doors = find_dataref("tu154b2/custom/lights/engines/eng1_reverse_doors")
simDR_eng1_vna33 = find_dataref("tu154b2/custom/lights/engines/eng1_vna33")
simDR_eng1_vna0 = find_dataref("tu154b2/custom/lights/engines/eng1_vna0")
simDR_eng1_bypass_valve= find_dataref("tu154b2/custom/lights/engines/eng1_bypass_valve")
simDR_eng1_filter_fail = find_dataref("tu154b2/custom/lights/engines/eng1_filter_fail")
simDR_eng1_oil_p = find_dataref("tu154b2/custom/lights/engines/eng1_oil_p")
simDR_eng1_fuel_p = find_dataref("tu154b2/custom/lights/engines/eng1_fuel_p")
simDR_eng1_oil_level = find_dataref("tu154b2/custom/lights/engines/eng1_oil_level")
simDR_eng1_chips = find_dataref("tu154b2/custom/lights/engines/eng1_chips")
simDR_eng1_t_high = find_dataref("tu154b2/custom/lights/engines/eng1_t_high")
simDR_eng1_stop = find_dataref("sim/custom/lights/engines/eng1_stop_gas")
simDR_eng1_dangerous_vibro = find_dataref("tu154b2/custom/lights/engines/eng1_dangerous_vibro")
simDR_eng1_high_vibro = find_dataref("tu154b2/custom/lights/engines/eng1_high_vibro")
simDR_eng2_dangerous_vibro = find_dataref("tu154b2/custom/lights/engines/eng2_dangerous_vibro")
simDR_eng2_high_vibro = find_dataref("tu154b2/custom/lights/engines/eng2_high_vibro")
simDR_eng2_oil_level = find_dataref("tu154b2/custom/lights/engines/eng2_oil_level")
simDR_eng2_chips = find_dataref("tu154b2/custom/lights/engines/eng2_chips")
simDR_eng2_t_high = find_dataref("tu154b2/custom/lights/engines/eng2_t_high")
simDR_eng2_stop = find_dataref("sim/custom/lights/engines/eng2_stop_gas")
simDR_eng2_oil_p = find_dataref("tu154b2/custom/lights/engines/eng2_oil_p")
simDR_eng2_bypass_valve = find_dataref("tu154b2/custom/lights/engines/eng2_bypass_valve")
simDR_eng2_filter_fail = find_dataref("tu154b2/custom/lights/engines/eng2_filter_fail")
simDR_eng2_vna33 = find_dataref("tu154b2/custom/lights/engines/eng2_vna33")
simDR_eng2_vna0 = find_dataref("tu154b2/custom/lights/engines/eng2_vna0")
simDR_eng_at_on = find_dataref("tu154b2/custom/lights/engines/eng_at_on")
simDR_eng_block = find_dataref("tu154b2/custom/lights/engines/eng_block")
simDR_eng3_dangerous_vibro = find_dataref("tu154b2/custom/lights/engines/eng3_dangerous_vibro")
simDR_eng3_high_vibro = find_dataref("tu154b2/custom/lights/engines/eng3_high_vibro")
simDR_eng3_oil_level= find_dataref("tu154b2/custom/lights/engines/eng3_oil_level")
simDR_eng3_chips = find_dataref("tu154b2/custom/lights/engines/eng3_chips")
simDR_eng3_t_high = find_dataref("tu154b2/custom/lights/engines/eng3_t_high")
simDR_eng3_stop = find_dataref("sim/custom/lights/engines/eng3_stop_gas")
simDR_eng3_oil_p = find_dataref("tu154b2/custom/lights/engines/eng3_oil_p")
simDR_eng3_fuel_p = find_dataref("tu154b2/custom/lights/engines/eng3_fuel_p")
simDR_eng3_bypass_valve = find_dataref("tu154b2/custom/lights/engines/eng3_bypass_valve")
simDR_eng3_filter_fail = find_dataref("tu154b2/custom/lights/engines/eng3_filter_fail")
simDR_eng3_vna33 = find_dataref("tu154b2/custom/lights/engines/eng3_vna33")
simDR_eng3_vna0 = find_dataref("tu154b2/custom/lights/engines/eng3_vna0")
simDR_eng3_reverse_lock = find_dataref("tu154b2/custom/lights/engines/eng3_reverse_lock")
simDR_eng3_reverse_doors = find_dataref("tu154b2/custom/lights/engines/eng3_reverse_doors")
simDR_ra56_pitch_fail_1 = find_dataref("tu154b2/custom/lights/ra56_pitch_fail_1")
simDR_ra56_pitch_fail_2 = find_dataref("tu154b2/custom/lights/ra56_pitch_fail_2")
simDR_ra56_pitch_fail_3 = find_dataref("tu154b2/custom/lights/ra56_pitch_fail_3")
simDR_ra56_roll_fail_1 = find_dataref("tu154b2/custom/lights/ra56_roll_fail_1")
simDR_ra56_roll_fail_2 = find_dataref("tu154b2/custom/lights/ra56_roll_fail_2")
simDR_ra56_roll_fail_3 = find_dataref("tu154b2/custom/lights/ra56_roll_fail_3")
simDR_ra56_course_fail_1 = find_dataref("tu154b2/custom/lights/ra56_course_fail_1")
simDR_ra56_course_fail_2 = find_dataref("tu154b2/custom/lights/ra56_course_fail_2")
simDR_ra56_course_fail_3 = find_dataref("tu154b2/custom/lights/ra56_course_fail_3")
simDR_nvu_no_reserve = find_dataref("tu154b2/custom/lights/nvu_no_reserve")
simDR_smoke_1 = find_dataref("tu154b2/custom/lights/fire/smoke_1")
simDR_smoke_1_but = find_dataref("sim/custom/b2/smoke_1_button")
simDR_smoke_2_but = find_dataref("sim/custom/b2/smoke_2_button")
simDR_smoke_zone2_left = find_dataref("tu154b2/custom/lights/fire/smoke_zone2_left")
simDR_smoke_zone3 = find_dataref("tu154b2/custom/lights/fire/smoke_zone3")
simDR_smoke_zone2_right = find_dataref("tu154b2/custom/lights/fire/smoke_zone2_right")
simDR_smoke_zone4 = find_dataref("tu154b2/custom/lights/fire/smoke_zone4")
simDR_smoke_2 = find_dataref("tu154b2/custom/lights/fire/smoke_2")
simDR_smoke_zone5_left = find_dataref("tu154b2/custom/lights/fire/smoke_zone5_left")
simDR_smoke_zone5_right = find_dataref("tu154b2/custom/lights/fire/smoke_zone5_right")
simDR_smoke_zone6 = find_dataref("tu154b2/custom/lights/fire/smoke_zone6")
simDR_fire_ng = find_dataref("tu154b2/custom/lights/button/fire_ng")
simDR_fire_eng_1 = find_dataref("tu154b2/custom/lights/fire/fire_eng_1")
simDR_fire_eng_2 = find_dataref("tu154b2/custom/lights/fire/fire_eng_2")
simDR_fire_eng_3 = find_dataref("tu154b2/custom/lights/fire/fire_eng_3")
simDR_fire_apu = find_dataref("tu154b2/custom/lights/fire/fire_apu")
simDR_fire_turn_1 = find_dataref("tu154b2/custom/lights/button/fire_turn_1")
simDR_fire_turn_2 = find_dataref("tu154b2/custom/lights/button/fire_turn_2")
simDR_fire_turn_3 = find_dataref("tu154b2/custom/lights/button/fire_turn_3")
simDR_overheat_eng_1 = find_dataref("tu154b2/custom/lights/fire/overheat_eng_1")
simDR_overheat_eng_2 = find_dataref("tu154b2/custom/lights/fire/overheat_eng_2")
simDR_overheat_eng_3 = find_dataref("tu154b2/custom/lights/fire/overheat_eng_3")
simDR_fuel_off_eng_1 = find_dataref("tu154b2/custom/lights/fire/fuel_off_eng_1")
simDR_fuel_off_eng_2 = find_dataref("tu154b2/custom/lights/fire/fuel_off_eng_2")
simDR_fuel_off_eng_3 = find_dataref("tu154b2/custom/lights/fire/fuel_off_eng_3")
simDR_check_overheat = find_dataref("tu154b2/custom/lights/fire/check_overheat")
simDR_turn_on_spz = find_dataref("tu154b2/custom/lights/fire/turn_on_spz")
simDR_left_front_pax_door = find_dataref("tu154b2/custom/lights/left_front_pax_door")
simDR_left_mid_pax_door = find_dataref("tu154b2/custom/lights/left_mid_pax_door")
simDR_other_hatches = find_dataref("tu154b2/custom/lights/other_hatches")
simDR_right_mid_pax_door = find_dataref("tu154b2/custom/lights/right_mid_pax_door")
simDR_cargo_front_door = find_dataref("tu154b2/custom/lights/cargo_front_door")
simDR_cargo_back_door = find_dataref("tu154b2/custom/lights/cargo_back_door")
simDR_turn63_lamp = find_dataref("tu154b2/custom/lights/turn63_lamp")
simDR_nosewheel_turn_off = find_dataref("tu154b2/custom/lights/nosewheel_turn_off")
simDR_busters_off = find_dataref("tu154b2/custom/lights/busters_off")
simDR_water_level_1 = find_dataref("tu154b2/custom/lights/water_level_1")
simDR_water_level_12 = find_dataref("tu154b2/custom/lights/water_level_12")
simDR_water_level_14 = find_dataref("tu154b2/custom/lights/water_level_14")
simDR_water_level_0 = find_dataref("tu154b2/custom/lights/water_level_0")
simDR_gears_red_left_eng = find_dataref("tu154b2/custom/lights/gears_red_left_eng")
simDR_gears_red_front_eng = find_dataref("tu154b2/custom/lights/gears_red_front_eng")
simDR_gears_red_right_eng = find_dataref("tu154b2/custom/lights/gears_red_right_eng")
simDR_gears_green_left_eng = find_dataref("tu154b2/custom/lights/gears_green_left_eng")
simDR_gears_green_front_eng = find_dataref("tu154b2/custom/lights/gears_green_front_eng")
simDR_gears_green_right_eng = find_dataref("tu154b2/custom/lights/gears_green_right_eng")
simDR_eng2_fuel_p = find_dataref("tu154b2/custom/lights/engines/eng2_fuel_p")
simDR_transponder1_fail = find_dataref("tu154b2/custom/lights/small/transponder1_fail")
simDR_transponder1_kd = find_dataref("tu154b2/custom/lights/small/transponder1_kd")
simDR_transponder1_kp = find_dataref("tu154b2/custom/lights/small/transponder1_kp")
simDR_leftside_yellow = find_dataref("tu154b2/custom/lights/small/leftside_yellow")
simDR_front_hydr_fail_1 = find_dataref("tu154b2/custom/lights/small/front_hydr_fail_1")
simDR_front_hydr_fail_2 = find_dataref("tu154b2/custom/lights/small/front_hydr_fail_2")
simDR_front_hydr_fail_3 = find_dataref("tu154b2/custom/lights/small/front_hydr_fail_3")
simDR_front_hydr_fail_4 = find_dataref("tu154b2/custom/lights/small/front_hydr_fail_4")
simDR_stu_roll = find_dataref("tu154b2/custom/lights/small/stu_roll")
simDR_stu_pitch = find_dataref("tu154b2/custom/lights/small/stu_pitch")
simDR_stu_toga = find_dataref("tu154b2/custom/lights/small/stu_toga")
simDR_at_2 = find_dataref("tu154b2/custom/lights/small/at_2")
simDR_at_1 = find_dataref("tu154b2/custom/lights/small/at_1")
simDR_nav_1_to = find_dataref("tu154b2/custom/lights/small/nav_1_to")
simDR_nav_1_from = find_dataref("tu154b2/custom/lights/small/nav_1_from")
simDR_nav_2_to = find_dataref("tu154b2/custom/lights/small/nav_2_to")
simDR_nav_2_from = find_dataref("tu154b2/custom/lights/small/nav_2_from")
simDR_bkk_ok = find_dataref("tu154b2/custom/lights/small/bkk_ok")
simDR_heat_ok_1 = find_dataref("tu154b2/custom/lights/small/heat_ok_1")
simDR_heat_ok_2 = find_dataref("tu154b2/custom/lights/small/heat_ok_2")
simDR_heat_ok_3 = find_dataref("tu154b2/custom/lights/small/heat_ok_3")
simDR_left_bus_on_tr2 = find_dataref("tu154b2/custom/lights/small/left_bus_on_tr2")
simDR_right_bus_on_tr1 = find_dataref("tu154b2/custom/lights/small/right_bus_on_tr1")
simDR_pts250_n1 = find_dataref("tu154b2/custom/lights/small/pts250_n1")
simDR_pts250_n2 = find_dataref("tu154b2/custom/lights/small/pts250_n2")
simDR_vu_on_1 = find_dataref("tu154b2/custom/lights/small/vu_on_1")
simDR_turn_off_bat_1 = find_dataref("tu154b2/custom/lights/small/turn_off_bat_1")
simDR_left_bus_use_bat = find_dataref("tu154b2/custom/lights/small/left_bus_use_bat")
simDR_turn_off_bat_3 = find_dataref("tu154b2/custom/lights/small/turn_off_bat_3")
simDR_vu_on_2 = find_dataref("tu154b2/custom/lights/small/vu_on_2")
simDR_turn_off_bat_2 = find_dataref("tu154b2/custom/lights/small/turn_off_bat_2")
simDR_right_bus_use_bat = find_dataref("tu154b2/custom/lights/small/right_bus_use_bat")
simDR_turn_off_bat_4 = find_dataref("tu154b2/custom/lights/small/turn_off_bat_4")
simDR_bus_connected = find_dataref("tu154b2/custom/lights/small/bus_connected")
simDR_emerg_inv_115 = find_dataref("tu154b2/custom/lights/small/emerg_inv_115")
simDR_bus_npk_1 = find_dataref("tu154b2/custom/lights/small/bus_npk_1")
simDR_bus_npk_2 = find_dataref("tu154b2/custom/lights/small/bus_npk_2")
simDR_apu_gen_on = find_dataref("tu154b2/custom/lights/small/apu_gen_on")
simDR_fuel_2500 = find_dataref("tu154b2/custom/lights/small/fuel_2500")
simDR_starter_high_rpm_1 = find_dataref("tu154b2/custom/lights/small/starter_high_rpm_1")
simDR_starter_high_rpm_2 = find_dataref("tu154b2/custom/lights/small/starter_high_rpm_2")
simDR_fuel_tank1_used = find_dataref("tu154b2/custom/lights/small/fuel_tank1_used")
simDR_starter_high_rpm_3 = find_dataref("tu154b2/custom/lights/small/starter_high_rpm_3")
simDR_fuel_flow_auto_fail = find_dataref("tu154b2/custom/lights/small/fuel_flow_auto_fail")
simDR_fuel_cut_off_1 = find_dataref("tu154b2/custom/lights/small/fuel_cut_off_1")
simDR_fuel_cut_off_2 = find_dataref("tu154b2/custom/lights/small/fuel_cut_off_2")
simDR_fuel_cut_off_3 = find_dataref("tu154b2/custom/lights/small/fuel_cut_off_3")
simDR_fuel_level_automat = find_dataref("tu154b2/custom/lights/small/fuel_level_automat")
simDR_skv_overheat = find_dataref("tu154b2/custom/lights/small/skv_overheat")
simDR_eng_hydr_fail_1 = find_dataref("tu154b2/custom/lights/small/eng_hydr_fail_1")
simDR_eng_hydr_fail_2 = find_dataref("tu154b2/custom/lights/small/eng_hydr_fail_2")
simDR_eng_hydr_fail_3 = find_dataref("tu154b2/custom/lights/small/eng_hydr_fail_3")
simDR_eng_hydr_fail_4 = find_dataref("tu154b2/custom/lights/small/eng_hydr_fail_4")
simDR_skv_overpress_left = find_dataref("tu154b2/custom/lights/small/skv_overpress_left")
simDR_skv_overpress_right = find_dataref("tu154b2/custom/lights/small/skv_overpress_right")
simDR_skv_bleed_fail_1 = find_dataref("tu154b2/custom/lights/small/skv_bleed_fail_1")
simDR_skv_bleed_fail_2 = find_dataref("tu154b2/custom/lights/small/skv_bleed_fail_2")
simDR_skv_bleed_fail_3 = find_dataref("tu154b2/custom/lights/small/skv_bleed_fail_3")
simDR_skv_tail_temp = find_dataref("tu154b2/custom/lights/small/skv_tail_temp")
simDR_skv_bleed_closed_1 = find_dataref("tu154b2/custom/lights/small/skv_bleed_closed_1")
simDR_skv_bleed_closed_2 = find_dataref("tu154b2/custom/lights/small/skv_bleed_closed_2")
simDR_skv_bleed_closed_3 = find_dataref("tu154b2/custom/lights/small/skv_bleed_closed_3")
simDR_apd_work_1 = find_dataref("tu154b2/custom/lights/small/apd_work_1")
simDR_apd_work_2 = find_dataref("tu154b2/custom/lights/small/apd_work_2")
simDR_apd_work_3 = find_dataref("tu154b2/custom/lights/small/apd_work_3")
simDR_close_toilet = find_dataref("tu154b2/custom/lights/small/close_toilet")
simDR_srd_low_press = find_dataref("tu154b2/custom/lights/small/srd_low_press")
simDR_srd_overpress = find_dataref("tu154b2/custom/lights/small/srd_overpress")
simDR_soi_ice_detected = find_dataref("tu154b2/custom/lights/small/soi_ice_detected")
simDR_soi_work = find_dataref("tu154b2/custom/lights/small/soi_work")
simDR_tail_temp_high = find_dataref("tu154b2/custom/lights/small/tail_temp_high")
simDR_lavatory_heat = find_dataref("tu154b2/custom/lights/small/lavatory_heat")
simDR_galley_heat = find_dataref("tu154b2/custom/lights/small/galley_heat")
simDR_turn_on_aux = find_dataref("tu154b2/custom/lights/small/turn_on_aux")
simDR_tks_contr_fail = find_dataref("tu154b2/custom/lights/small/tks_contr_fail")

simDR_wpt_lamp = find_dataref("tu154b2/custom/lights/wpt_lamp")
simDR_msg_lamp = find_dataref("tu154b2/custom/lights/msg_lamp")

simDR_trim_p_light = find_dataref("tu154b2/custom/lights/trimm_zero_pitch")
simDR_trim_r_light = find_dataref("tu154b2/custom/lights/trimm_zero_roll")
simDR_trim_c_light = find_dataref("tu154b2/custom/lights/trimm_zero_course")
simDR_fuel_flow_from_4 =  find_dataref("tu154b2/custom/lights/small/fuel_flow_from_4")
simDR_fuel_flow_from_2 =  find_dataref("tu154b2/custom/lights/small/fuel_flow_from_2")
simDR_fuel_reserv_trans_left =  find_dataref("tu154b2/custom/lights/small/fuel_reserv_trans_left")
simDR_fuel_reserv_trans_right =  find_dataref("tu154b2/custom/lights/small/fuel_reserv_trans_right")
simDR_fuel_porc_reserv =  find_dataref("tu154b2/custom/lights/small/fuel_porc_reserv")
simDR_fuel_flow_from_3 =  find_dataref("tu154b2/custom/lights/small/fuel_flow_from_3")
simDR_msrp_mars =  find_dataref("tu154b2/custom/lights/small/msrp_mars")
simDR_msrp_up2 =  find_dataref("tu154b2/custom/lights/small/msrp_up2")
simDR_msrp_mlp_aux =  find_dataref("tu154b2/custom/lights/small/msrp_mlp_aux")
simDR_msrp_mlp_main =  find_dataref("tu154b2/custom/lights/small/msrp_mlp_main")
simDR_antiice_wings =  find_dataref("tu154b2/custom/lights/small/antiice_wings")
simDR_antiice_eng_3 =  find_dataref("tu154b2/custom/lights/small/antiice_eng_3")
simDR_antiice_eng_2 =  find_dataref("tu154b2/custom/lights/small/antiice_eng_2")
simDR_antiice_slats =  find_dataref("tu154b2/custom/lights/small/antiice_slats")
simDR_antiice_eng_1 =  find_dataref("tu154b2/custom/lights/small/antiice_eng_1")
simDR_vd15_lamp =  find_dataref("tu154b2/custom/lights/small/vd15_lamp")
simDR_absu_work =  find_dataref("tu154b2/custom/lights/absu_work")
simDR_tks_main_fail =  find_dataref("tu154b2/custom/lights/small/tks_main_fail")
simDR_auasp_lamp =  find_dataref("tu154b2/custom/lights/auasp_lamp")
simDR_exit_lamp =  find_dataref("tu154b2/custom/lights/exit_lamp")
simDR_pnp_rsbn_left =  find_dataref("tu154b2/custom/lights/small/pnp_rsbn_left")
simDR_pnp_sp_left =  find_dataref("tu154b2/custom/lights/small/pnp_sp_left")
simDR_pnp_vor_left =  find_dataref("tu154b2/custom/lights/small/pnp_vor_left")
simDR_pnp_nv_left =  find_dataref("tu154b2/custom/lights/small/pnp_nv_left")
simDR_pnp_nv_right =  find_dataref("tu154b2/custom/lights/small/pnp_nv_right")
simDR_pnp_vor_right =  find_dataref("tu154b2/custom/lights/small/pnp_vor_right")
simDR_pnp_sp_right =  find_dataref("tu154b2/custom/lights/small/pnp_sp_right")
simDR_pnp_rsbn_right =  find_dataref("tu154b2/custom/lights/small/pnp_rsbn_right")
simDR_sp50_c1 =  find_dataref("tu154b2/custom/lights/small/sp50_c1")
simDR_sp50_g1 =  find_dataref("tu154b2/custom/lights/small/sp50_g1")
simDR_sp50_g2 =  find_dataref("tu154b2/custom/lights/small/sp50_g2")
simDR_sp50_c2 =  find_dataref("tu154b2/custom/lights/small/sp50_c2")
simDR_transponder_green =  find_dataref("tu154b2/custom/lights/small/transponder_green")
simDR_dme_km_left =  find_dataref("tu154b2/custom/lights/small/dme_km_left")
simDR_dme_mile_left =  find_dataref("tu154b2/custom/lights/small/dme_mile_left")
simDR_dme_km_right =  find_dataref("tu154b2/custom/lights/small/dme_km_right")
simDR_dme_mile_right =  find_dataref("tu154b2/custom/lights/small/dme_mile_right")
simDR_oil_meter_1 =  find_dataref("tu154b2/custom/lights/small/oil_meter_1")
simDR_oil_meter_2 =  find_dataref("tu154b2/custom/lights/small/oil_meter_2")
simDR_oil_meter_3 =  find_dataref("tu154b2/custom/lights/small/oil_meter_3")
simDR_marker_2 =  find_dataref("tu154b2/custom/lights/marker_2")
simDR_marker_3 =  find_dataref("tu154b2/custom/lights/marker_3")
simDR_marker_1 =  find_dataref("tu154b2/custom/lights/marker_1")
simDR_stab_m =  find_dataref("tu154b2/custom/lights/stab_m")
simDR_vor_lamp =  find_dataref("tu154b2/custom/lights/vor_lamp")
simDR_stab_v =  find_dataref("tu154b2/custom/lights/stab_v")
simDR_nvu_lamp =  find_dataref("tu154b2/custom/lights/nvu_lamp")
simDR_stab_h =  find_dataref("tu154b2/custom/lights/stab_h")
simDR_stab_roll =  find_dataref("tu154b2/custom/lights/stab_roll")
simDR_stab_pitch =  find_dataref("tu154b2/custom/lights/stab_pitch")
simDR_zk_lamp =  find_dataref("tu154b2/custom/lights/zk_lamp")
simDR_thrust_automat =  find_dataref("tu154b2/custom/lights/thrust_automat")
simDR_course =  find_dataref("tu154b2/custom/lights/course")
simDR_glideslope =  find_dataref("tu154b2/custom/lights/glideslope")
simDR_no_ag_controll =  find_dataref("tu154b2/custom/lights/no_ag_controll")
simDR_speed_high =  find_dataref("tu154b2/custom/lights/speed_high")
simDR_check_alt_left =  find_dataref("tu154b2/custom/lights/check_alt_left")
simDR_check_alt_right =  find_dataref("tu154b2/custom/lights/check_alt_right")
simDR_sso_connect =  find_dataref("tu154b2/custom/lights/sso_connect")
simDR_ofuel_less_2500 =  find_dataref("tu154b2/custom/lights/fuel_less_2500")
simDR_sso_danger =  find_dataref("tu154b2/custom/lights/sso_danger")
simDR_roll_left_high =  find_dataref("tu154b2/custom/lights/roll_left_high")
simDR_toga =  find_dataref("tu154b2/custom/lights/toga")
simDR_decision_height =  find_dataref("tu154b2/custom/lights/decision_height")
simDR_roll_right_high =  find_dataref("tu154b2/custom/lights/roll_right_high")
simDR_pull_up =  find_dataref("tu154b2/custom/lights/pull_up")
simDR_wrong_trimm =  find_dataref("tu154b2/custom/lights/wrong_trimm")
simDR_controll_roll =  find_dataref("tu154b2/custom/lights/controll_roll")
simDR_controll_pitch =  find_dataref("tu154b2/custom/lights/controll_pitch")
simDR_yoke_sign =  find_dataref("tu154b2/custom/lights/yoke_sign")
simDR_triangle =  find_dataref("tu154b2/custom/lights/triangle")
simDR_controll_thrust =  find_dataref("tu154b2/custom/lights/controll_thrust")
simDR_course_lim =  find_dataref("tu154b2/custom/lights/course_lim")
simDR_gs_lim =  find_dataref("tu154b2/custom/lights/gs_lim")
simDR_fire =  find_dataref("tu154b2/custom/lights/fire")
simDR_damper_course =  find_dataref("tu154b2/custom/lights/damper_course")
simDR_damper_roll =  find_dataref("tu154b2/custom/lights/damper_roll")
simDR_damper_pitch =  find_dataref("tu154b2/custom/lights/damper_pitch")
simDR_pitch_control_fail =  find_dataref("tu154b2/custom/lights/pitch_control_fail")
simDR_roll_control_fail =  find_dataref("tu154b2/custom/lights/roll_control_fail")
simDR_no_reserve_c =  find_dataref("tu154b2/custom/lights/no_reserve_c")
simDR_no_reserve_g =  find_dataref("tu154b2/custom/lights/no_reserve_g")
simDR_ga_main_fail =  find_dataref("tu154b2/custom/lights/ga_main_fail")
simDR_ga_reserve_fail =  find_dataref("tu154b2/custom/lights/ga_reserve_fail")
simDR_gs_low =  find_dataref("tu154b2/custom/lights/gs_low")
simDR_srpbz_fail =  find_dataref("tu154b2/custom/lights/srpbz_fail")
simDR_warning_terrain =  find_dataref("tu154b2/custom/lights/warning_terrain")
simDR_azimuth_autonom =  find_dataref("tu154b2/custom/lights/azimuth_autonom")
simDR_change_ch_o =  find_dataref("tu154b2/custom/lights/change_ch_o")
simDR_diss_memory =  find_dataref("tu154b2/custom/lights/diss_memory")
simDR_correct_on =  find_dataref("tu154b2/custom/lights/correct_on")
simDR_dist_autonom =  find_dataref("tu154b2/custom/lights/dist_autonom")
simDR_sns_lamp =  find_dataref("tu154b2/custom/lights/sns_lamp")
simDR_nvu_vor_automat =  find_dataref("tu154b2/custom/lights/nvu_vor_automat")
simDR_mgv_control_fail =  find_dataref("tu154b2/custom/lights/mgv_control_fail")
simDR_nvu_fail =  find_dataref("tu154b2/custom/lights/nvu_fail")
simDR_stuard_call =  find_dataref("tu154b2/custom/lights/stuard_call")
simDR_cockpit_p_low =  find_dataref("tu154b2/custom/lights/cockpit_p_low")
simDR_fp_eng_fail_1 =  find_dataref("tu154b2/custom/lights/fp_eng_fail_1")
simDR_fp_reverse_1 =  find_dataref("tu154b2/custom/lights/fp_reverse_1")
simDR_fp_eng_fail_2 =  find_dataref("tu154b2/custom/lights/fp_eng_fail_2")
simDR_fp_eng_fail_3 =  find_dataref("tu154b2/custom/lights/fp_eng_fail_3")
simDR_fp_reverse_3 =  find_dataref("tu154b2/custom/lights/fp_reverse_3")
simDR_stab_work =  find_dataref("tu154b2/custom/lights/stab_work")
simDR_flaps_1_valve =  find_dataref("tu154b2/custom/lights/flaps_1_valve")
simDR_flaps_2_valve =  find_dataref("tu154b2/custom/lights/flaps_2_valve")
simDR_spoilers_mid_left =  find_dataref("tu154b2/custom/lights/spoilers_mid_left")
simDR_spoilers_inn_left =  find_dataref("tu154b2/custom/lights/spoilers_inn_left")
simDR_spoilers_inn_right =  find_dataref("tu154b2/custom/lights/spoilers_inn_right")
simDR_spoilers_mid_right =  find_dataref("tu154b2/custom/lights/spoilers_mid_right")
simDR_flaps_unsync =  find_dataref("tu154b2/custom/lights/flaps_unsync")
simDR_slats_unsync =  find_dataref("tu154b2/custom/lights/slats_unsync")
simDR_gears_green_left =  find_dataref("tu154b2/custom/lights/gears_green_left")
simDR_gears_green_front =  find_dataref("tu154b2/custom/lights/gears_green_front")
simDR_gears_green_right =  find_dataref("tu154b2/custom/lights/gears_green_right")
simDR_gears_red_left =  find_dataref("tu154b2/custom/lights/gears_red_left")
simDR_gears_red_front =  find_dataref("tu154b2/custom/lights/gears_red_front")
simDR_gears_red_right =  find_dataref("tu154b2/custom/lights/gears_red_right")
simDR_gears_not_ext =  find_dataref("tu154b2/custom/lights/gears_not_ext")
simDR_alpha_high =  find_dataref("tu154b2/custom/lights/alpha_high")
simDR_g_force_high =  find_dataref("tu154b2/custom/lights/g_force_high")


simDR_lamp_test_eng = find_dataref("tu154b2/custom/buttons/lamp_test_engines")
simDR_lamp_test_fire = find_dataref("tu154b2/custom/buttons/lamp_test_fire_panel")


-- lights list end




wpt_lamp = deferred_dataref("sim/custom/lights/wpt_lamp_new", "number")
msg_lamp = deferred_dataref("sim/custom/lights/msg_lamp_new", "number")
trim_p_light = deferred_dataref("sim/custom/lights/trimm_zero_pitch_new", "number")
trim_r_light = deferred_dataref("sim/custom/lights/trimm_zero_roll_new", "number")
trim_c_light = deferred_dataref("sim/custom/lights/trimm_zero_course_new", "number")
fuel_flow_from_4 =  deferred_dataref("sim/custom/lights/small/fuel_flow_from_4_new", "number")
fuel_tank2_right_fail =  deferred_dataref("sim/custom/lights/small/fuel_tank2_right_fail_new", "number")
fuel_flow_from_2 =  deferred_dataref("sim/custom/lights/small/fuel_flow_from_2_new", "number")
fuel_tank3_left_fail =  deferred_dataref("sim/custom/lights/small/fuel_tank3_left_fail_new", "number")
fuel_tank2_left_fail =  deferred_dataref("sim/custom/lights/small/fuel_tank2_left_fail_new", "number")
fuel_tank3_right_fail =  deferred_dataref("sim/custom/lights/small/fuel_tank3_right_fail_new", "number")
fuel_reserv_trans_left =  deferred_dataref("sim/custom/lights/small/fuel_reserv_trans_left_new", "number")
fuel_reserv_trans_right =  deferred_dataref("sim/custom/lights/small/fuel_reserv_trans_right_new", "number")
fuel_porc_reserv =  deferred_dataref("sim/custom/lights/small/fuel_porc_reserv_new", "number")
fuel_flow_from_3 =  deferred_dataref("sim/custom/lights/small/fuel_flow_from_3_new", "number")
msrp_mars =  deferred_dataref("sim/custom/lights/small/msrp_mars_new", "number")
msrp_up2 =  deferred_dataref("sim/custom/lights/small/msrp_up2_new", "number")
msrp_mlp_aux =  deferred_dataref("sim/custom/lights/small/msrp_mlp_aux_new", "number")
msrp_mlp_main =  deferred_dataref("sim/custom/lights/small/msrp_mlp_main_new", "number")
antiice_wings =  deferred_dataref("sim/custom/lights/small/antiice_wings_new", "number")
antiice_eng_3 =  deferred_dataref("sim/custom/lights/small/antiice_eng_3_new", "number")
antiice_eng_2 =  deferred_dataref("sim/custom/lights/small/antiice_eng_2_new", "number")
antiice_slats =  deferred_dataref("sim/custom/lights/small/antiice_slats_new", "number")
antiice_eng_1 =  deferred_dataref("sim/custom/lights/small/antiice_eng_1_new", "number")
vd15_lamp =  deferred_dataref("sim/custom/lights/small/vd15_lamp_new", "number")
absu_work =  deferred_dataref("sim/custom/lights/absu_work_new", "number")
tks_main_fail =  deferred_dataref("sim/custom/lights/small/tks_main_fail_new", "number")
auasp_lamp =  deferred_dataref("sim/custom/lights/auasp_lamp_new", "number")
exit_lamp =  deferred_dataref("sim/custom/lights/exit_lamp_new", "number")
pnp_rsbn_left =  deferred_dataref("sim/custom/lights/small/pnp_rsbn_left_new", "number")
pnp_sp_left =  deferred_dataref("sim/custom/lights/small/pnp_sp_left_new", "number")
pnp_vor_left =  deferred_dataref("sim/custom/lights/small/pnp_vor_left_new", "number")
pnp_nv_left =  deferred_dataref("sim/custom/lights/small/pnp_nv_left_new", "number")
pnp_nv_right =  deferred_dataref("sim/custom/lights/small/pnp_nv_right_new", "number")
pnp_vor_right =  deferred_dataref("sim/custom/lights/small/pnp_vor_right_new", "number")
pnp_sp_right =  deferred_dataref("sim/custom/lights/small/pnp_sp_right_new", "number")
pnp_rsbn_right =  deferred_dataref("sim/custom/lights/small/pnp_rsbn_right_new", "number")
sp50_c1 =  deferred_dataref("sim/custom/lights/small/sp50_c1_new", "number")
sp50_g1 =  deferred_dataref("sim/custom/lights/small/sp50_g1_new", "number")
sp50_g2 =  deferred_dataref("sim/custom/lights/small/sp50_g2_new", "number")
sp50_c2 =  deferred_dataref("sim/custom/lights/small/sp50_c2_new", "number")
transponder_green =  deferred_dataref("sim/custom/lights/small/transponder_green_new", "number")
dme_km_left =  deferred_dataref("sim/custom/lights/small/dme_km_left_new", "number")
dme_mile_left =  deferred_dataref("sim/custom/lights/small/dme_mile_left_new", "number")
dme_km_right =  deferred_dataref("sim/custom/lights/small/dme_km_right_new", "number")
dme_mile_right =  deferred_dataref("sim/custom/lights/small/dme_mile_right_new", "number")
oil_meter_1 =  deferred_dataref("sim/custom/lights/small/oil_meter_1_new", "number")
oil_meter_2 =  deferred_dataref("sim/custom/lights/small/oil_meter_2_new", "number")
oil_meter_3 =  deferred_dataref("sim/custom/lights/small/oil_meter_3_new", "number")
marker_2 =  deferred_dataref("sim/custom/lights/marker_2_new", "number")
marker_3 =  deferred_dataref("sim/custom/lights/marker_3_new", "number")
marker_1 =  deferred_dataref("sim/custom/lights/marker_1_new", "number")
stab_m =  deferred_dataref("sim/custom/lights/stab_m_new", "number")
vor_lamp =  deferred_dataref("sim/custom/lights/vor_lamp_new", "number")
stab_v =  deferred_dataref("sim/custom/lights/stab_v_new", "number")
nvu_lamp =  deferred_dataref("sim/custom/lights/nvu_lamp_new", "number")
stab_h =  deferred_dataref("sim/custom/lights/stab_h_new", "number")
stab_roll =  deferred_dataref("sim/custom/lights/stab_roll_new", "number")
stab_pitch =  deferred_dataref("sim/custom/lights/stab_pitch_new", "number")
zk_lamp =  deferred_dataref("sim/custom/lights/zk_lamp_new", "number")
thrust_automat =  deferred_dataref("sim/custom/lights/thrust_automat_new", "number")
course =  deferred_dataref("sim/custom/lights/course_new", "number")
glideslope =  deferred_dataref("sim/custom/lights/glideslope_new", "number")
no_ag_controll =  deferred_dataref("sim/custom/lights/no_ag_controll_new", "number")
sns_lamp =  deferred_dataref("sim/custom/lights/sns_lamp_new", "number")
speed_high =  deferred_dataref("sim/custom/lights/speed_high_new", "number")
check_alt_left =  deferred_dataref("sim/custom/lights/check_alt_left_new", "number")
check_alt_right =  deferred_dataref("sim/custom/lights/check_alt_right_new", "number")
sso_connect =  deferred_dataref("sim/custom/lights/sso_connect_new", "number")
ofuel_less_2500 =  deferred_dataref("sim/custom/lights/fuel_less_2500_new", "number")
sso_danger =  deferred_dataref("sim/custom/lights/sso_danger_new", "number")
roll_left_high =  deferred_dataref("sim/custom/lights/roll_left_high_new", "number")
toga =  deferred_dataref("sim/custom/lights/toga_new", "number")
decision_height =  deferred_dataref("sim/custom/lights/decision_height_new", "number")
roll_right_high =  deferred_dataref("sim/custom/lights/roll_right_high_new", "number")
pull_up =  deferred_dataref("sim/custom/lights/pull_up_new", "number")
wrong_trimm =  deferred_dataref("sim/custom/lights/wrong_trimm_new", "number")
controll_roll =  deferred_dataref("sim/custom/lights/controll_roll_new", "number")
controll_pitch =  deferred_dataref("sim/custom/lights/controll_pitch_new", "number")
yoke_sign =  deferred_dataref("sim/custom/lights/yoke_sign_new", "number")
triangle =  deferred_dataref("sim/custom/lights/triangle_new", "number")
controll_thrust =  deferred_dataref("sim/custom/lights/controll_thrust_new", "number")
course_lim =  deferred_dataref("sim/custom/lights/course_lim_new", "number")
gs_lim =  deferred_dataref("sim/custom/lights/gs_lim_new", "number")
fire =  deferred_dataref("sim/custom/lights/fire_new", "number")
damper_course =  deferred_dataref("sim/custom/lights/damper_course_new", "number")
damper_roll =  deferred_dataref("sim/custom/lights/damper_roll_new", "number")
damper_pitch =  deferred_dataref("sim/custom/lights/damper_pitch_new", "number")
pitch_control_fail =  deferred_dataref("sim/custom/lights/pitch_control_fail_new", "number")
roll_control_fail =  deferred_dataref("sim/custom/lights/roll_control_fail_new", "number")
no_reserve_c =  deferred_dataref("sim/custom/lights/no_reserve_c_new", "number")
no_reserve_g =  deferred_dataref("sim/custom/lights/no_reserve_g_new", "number")
ga_main_fail =  deferred_dataref("sim/custom/lights/ga_main_fail_new", "number")
ga_reserve_fail =  deferred_dataref("sim/custom/lights/ga_reserve_fail_new", "number")
gs_low =  deferred_dataref("sim/custom/lights/gs_low_new", "number")
srpbz_fail =  deferred_dataref("sim/custom/lights/srpbz_fail_new", "number")
fp_eng_fail_3 =  deferred_dataref("sim/custom/lights/fp_eng_fail_3_new", "number")
fp_reverse_3 =  deferred_dataref("sim/custom/lights/fp_reverse_3_new", "number")
flaps_1_valve =  deferred_dataref("sim/custom/lights/flaps_1_valve_new", "number")
flaps_2_valve =  deferred_dataref("sim/custom/lights/flaps_2_valve_new", "number")
spoilers_mid_left =  deferred_dataref("sim/custom/lights/spoilers_mid_left_new", "number")
spoilers_inn_left =  deferred_dataref("sim/custom/lights/spoilers_inn_left_new", "number")
spoilers_inn_right =  deferred_dataref("sim/custom/lights/spoilers_inn_right_new", "number")
spoilers_mid_right =  deferred_dataref("sim/custom/lights/spoilers_mid_right_new", "number")
flaps_unsync =  deferred_dataref("sim/custom/lights/flaps_unsync_new", "number")
slats_unsync =  deferred_dataref("sim/custom/lights/slats_unsync_new", "number")
gears_green_left =  deferred_dataref("sim/custom/lights/gears_green_left_new", "number")
gears_green_front =  deferred_dataref("sim/custom/lights/gears_green_front_new", "number")
gears_green_right =  deferred_dataref("sim/custom/lights/gears_green_right_new", "number")
gears_red_left =  deferred_dataref("sim/custom/lights/gears_red_left_new", "number")
gears_red_front =  deferred_dataref("sim/custom/lights/gears_red_front_new", "number")
gears_red_right =  deferred_dataref("sim/custom/lights/gears_red_right_new", "number")
gears_not_ext =  deferred_dataref("sim/custom/lights/gears_not_ext_new", "number")
alpha_high =  deferred_dataref("sim/custom/lights/alpha_high_new", "number")
g_force_high =  deferred_dataref("sim/custom/lights/g_force_high_new", "number")
warning_terrain =  deferred_dataref("sim/custom/lights/warning_terrain_new", "number")
azimuth_autonom =  deferred_dataref("sim/custom/lights/azimuth_autonom_new", "number")
change_ch_o =  deferred_dataref("sim/custom/lights/change_ch_o_new", "number")
diss_memory =  deferred_dataref("sim/custom/lights/diss_memory_new", "number")
correct_on =  deferred_dataref("sim/custom/lights/correct_on_new", "number")
dist_autonom =  deferred_dataref("sim/custom/lights/dist_autonom_new", "number")
nvu_vor_automat =  deferred_dataref("sim/custom/lights/nvu_vor_automat_new", "number")
mgv_control_fail =  deferred_dataref("sim/custom/lights/mgv_control_fail_new", "number")
nvu_fail =  deferred_dataref("sim/custom/lights/nvu_fail_new", "number")
stuard_call =  deferred_dataref("sim/custom/lights/stuard_call_new", "number")
cockpit_p_low =  deferred_dataref("sim/custom/lights/cockpit_p_low_new", "number")
fp_eng_fail_1 =  deferred_dataref("sim/custom/lights/fp_eng_fail_1_new", "number")
fp_reverse_1 =  deferred_dataref("sim/custom/lights/fp_reverse_1_new", "number")
fp_eng_fail_2 =  deferred_dataref("sim/custom/lights/fp_eng_fail_2_new", "number")

pta6_fail = deferred_dataref("sim/custom/lights/apu/pta6_fail_new", "number")
start_apu = deferred_dataref("sim/custom/lights/apu/start_apu_new", "number")
high_rpm = deferred_dataref("sim/custom/lights/apu/high_rpm_new", "number")
high_temp = deferred_dataref("sim/custom/lights/apu/high_temp_new", "number")
work_mode = deferred_dataref("sim/custom/lights/apu/work_mode_new", "number")
start_ready = deferred_dataref("sim/custom/lights/apu/start_ready_new", "number")
low_oil_press = deferred_dataref("sim/custom/lights/apu/low_oil_press_new", "number")
fuel_press = deferred_dataref("sim/custom/lights/apu/fuel_press_new", "number")
low_oil = deferred_dataref("sim/custom/lights/apu/low_oil_new", "number")
doors_open = deferred_dataref("sim/custom/lights/apu/doors_open_new", "number")
eng1_reverse_lock = deferred_dataref("sim/custom/lights/engines/eng1_reverse_lock_new", "number")
eng1_reverse_doors = deferred_dataref("sim/custom/lights/engines/eng1_reverse_doors_new", "number")
eng1_vna33 = deferred_dataref("sim/custom/lights/engines/eng1_vna33_new", "number")
eng1_vna0 = deferred_dataref("sim/custom/lights/engines/eng1_vna0_new", "number")
eng1_bypass_valve= deferred_dataref("sim/custom/lights/engines/eng1_bypass_valve_new", "number")
eng1_filter_fail = deferred_dataref("sim/custom/lights/engines/eng1_filter_fail_new", "number")
eng1_oil_p = deferred_dataref("sim/custom/lights/engines/eng1_oil_p_new", "number")
eng1_fuel_p = deferred_dataref("sim/custom/lights/engines/eng1_fuel_p_new", "number")
eng1_oil_level = deferred_dataref("sim/custom/lights/engines/eng1_oil_level_new", "number")
eng1_chips = deferred_dataref("sim/custom/lights/engines/eng1_chips_new", "number")
eng1_t = deferred_dataref("sim/custom/lights/engines/eng1_t_high_new", "number")
eng1_stop = deferred_dataref("sim/custom/lights/engines/eng1_stop_gas_new", "number")
eng1_dangerous_vibro = deferred_dataref("sim/custom/lights/engines/eng1_dangerous_vibro_new", "number")
eng1_high_vibro = deferred_dataref("sim/custom/lights/engines/eng1_high_vibro_new", "number")
eng2_dangerous_vibro = deferred_dataref("sim/custom/lights/engines/eng2_dangerous_vibro_new", "number")
eng2_high_vibro = deferred_dataref("sim/custom/lights/engines/eng2_high_vibro_new", "number")
eng2_oil_level = deferred_dataref("sim/custom/lights/engines/eng2_oil_level_new", "number")
eng2_chips = deferred_dataref("sim/custom/lights/engines/eng2_chips_new", "number")
eng2_t = deferred_dataref("sim/custom/lights/engines/eng2_t_high_new", "number")
eng2_stop = deferred_dataref("sim/custom/lights/engines/eng2_stop_gas_new", "number")
eng2_oil_p = deferred_dataref("sim/custom/lights/engines/eng2_oil_p_new", "number")
eng2_bypass_valve = deferred_dataref("sim/custom/lights/engines/eng2_bypass_valve_new", "number")
eng2_filter_fail = deferred_dataref("sim/custom/lights/engines/eng2_filter_fail_new", "number")
eng2_vna33 = deferred_dataref("sim/custom/lights/engines/eng2_vna33_new", "number")
eng2_vna0 = deferred_dataref("sim/custom/lights/engines/eng2_vna0_new", "number")
eng_at_on = deferred_dataref("sim/custom/lights/engines/eng_at_on_new", "number")
eng_block = deferred_dataref("sim/custom/lights/engines/eng_block_new", "number")
eng3_dangerous_vibro = deferred_dataref("sim/custom/lights/engines/eng3_dangerous_vibro_new", "number")
eng3_high_vibro = deferred_dataref("sim/custom/lights/engines/eng3_high_vibro_new", "number")
eng3_oil_level= deferred_dataref("sim/custom/lights/engines/eng3_oil_level_new", "number")
eng3_chips = deferred_dataref("sim/custom/lights/engines/eng3_chips_new", "number")
eng3_t = deferred_dataref("sim/custom/lights/engines/eng3_t_high_new", "number")
eng3_stop = deferred_dataref("sim/custom/lights/engines/eng3_stop_gas_new", "number")
eng3_oil_p = deferred_dataref("sim/custom/lights/engines/eng3_oil_p_new", "number")
eng3_fuel_p = deferred_dataref("sim/custom/lights/engines/eng3_fuel_p_new", "number")
eng3_bypass_valve = deferred_dataref("sim/custom/lights/engines/eng3_bypass_valve_new", "number")
eng3_filter_fail = deferred_dataref("sim/custom/lights/engines/eng3_filter_fail_new", "number")
eng3_vna33 = deferred_dataref("sim/custom/lights/engines/eng3_vna33_new", "number")
eng3_vna0 = deferred_dataref("sim/custom/lights/engines/eng3_vna0_new", "number")
eng3_reverse_lock = deferred_dataref("sim/custom/lights/engines/eng3_reverse_lock_new", "number")
eng3_reverse_doors = deferred_dataref("sim/custom/lights/engines/eng3_reverse_doors_new", "number")
ra56_pitch_fail_1 = deferred_dataref("sim/custom/lights/ra56_pitch_fail_1_new", "number")
ra56_pitch_fail_2 = deferred_dataref("sim/custom/lights/ra56_pitch_fail_2_new", "number")
ra56_pitch_fail_3 = deferred_dataref("sim/custom/lights/ra56_pitch_fail_3_new", "number")
ra56_roll_fail_1 = deferred_dataref("sim/custom/lights/ra56_roll_fail_1_new", "number")
ra56_roll_fail_2 = deferred_dataref("sim/custom/lights/ra56_roll_fail_2_new", "number")
ra56_roll_fail_3 = deferred_dataref("sim/custom/lights/ra56_roll_fail_3_new", "number")
ra56_course_fail_1 = deferred_dataref("sim/custom/lights/ra56_course_fail_1_new", "number")
ra56_course_fail_2 = deferred_dataref("sim/custom/lights/ra56_course_fail_2_new", "number")
ra56_course_fail_3 = deferred_dataref("sim/custom/lights/ra56_course_fail_3_new", "number")
nvu_no_reserve = deferred_dataref("sim/custom/lights/nvu_no_reserve_new", "number")
smoke_1 = deferred_dataref("sim/custom/lights/fire/smoke_1_new", "number")
smoke_zone2_left = deferred_dataref("sim/custom/lights/fire/smoke_zone2_left_new", "number")
smoke_zone3 = deferred_dataref("sim/custom/lights/fire/smoke_zone3_new", "number")
smoke_zone2_right = deferred_dataref("sim/custom/lights/fire/smoke_zone2_right_new", "number")
smoke_zone4 = deferred_dataref("sim/custom/lights/fire/smoke_zone4_new", "number")
smoke_2 = deferred_dataref("sim/custom/lights/fire/smoke_2_new", "number")
smoke_zone5_left = deferred_dataref("sim/custom/lights/fire/smoke_zone5_left_new", "number")
smoke_zone5_right = deferred_dataref("sim/custom/lights/fire/smoke_zone5_right_new", "number")
smoke_zone6 = deferred_dataref("sim/custom/lights/fire/smoke_zone6_new", "number")
fire_ng = deferred_dataref("sim/custom/lights/button/fire_ng_new", "number")
fire_eng_1 = deferred_dataref("sim/custom/lights/fire/fire_eng_1_new", "number")
fire_eng_2 = deferred_dataref("sim/custom/lights/fire/fire_eng_2_new", "number")
fire_eng_3 = deferred_dataref("sim/custom/lights/fire/fire_eng_3_new", "number")
fire_switch = deferred_dataref("sim/custom/lights/fire/fire_switch", "number")
fire_turn_1 = deferred_dataref("sim/custom/lights/button/fire_turn_1_new", "number")
fire_turn_2 = deferred_dataref("sim/custom/lights/button/fire_turn_2_new", "number")
fire_turn_3 = deferred_dataref("sim/custom/lights/button/fire_turn_3_new", "number")
overheat_eng_1 = deferred_dataref("sim/custom/lights/fire/overheat_eng_1_new", "number")
overheat_eng_2 = deferred_dataref("sim/custom/lights/fire/overheat_eng_2_new", "number")
overheat_eng_3 = deferred_dataref("sim/custom/lights/fire/overheat_eng_3_new", "number")
fuel_off_eng_1 = deferred_dataref("sim/custom/lights/fire/fuel_off_eng_1_new", "number")
fuel_off_eng_2 = deferred_dataref("sim/custom/lights/fire/fuel_off_eng_2_new", "number")
fuel_off_eng_3 = deferred_dataref("sim/custom/lights/fire/fuel_off_eng_3_new", "number")
check_overheat = deferred_dataref("sim/custom/lights/fire/check_overheat_new", "number")
fire_apu = deferred_dataref("sim/custom/lights/fire/fire_apu_new", "number")
turn_on_spz = deferred_dataref("sim/custom/lights/fire/turn_on_spz_new", "number")
left_front_pax_door = deferred_dataref("sim/custom/lights/left_front_pax_door_new", "number")
left_mid_pax_door = deferred_dataref("sim/custom/lights/left_mid_pax_door_new", "number")
other_hatches = deferred_dataref("sim/custom/lights/other_hatches_new", "number")
right_mid_pax_door = deferred_dataref("sim/custom/lights/right_mid_pax_door_new", "number")
cargo_front_door = deferred_dataref("sim/custom/lights/cargo_front_door_new", "number")
cargo_back_door = deferred_dataref("sim/custom/lights/cargo_back_door_new", "number")
turn63_lamp = deferred_dataref("sim/custom/lights/turn63_lamp_new", "number")
nosewheel_turn_off = deferred_dataref("sim/custom/lights/nosewheel_turn_off_new", "number")
busters_off = deferred_dataref("sim/custom/lights/busters_off_new", "number")
water_level_1 = deferred_dataref("sim/custom/lights/water_level_1_new", "number")
water_level_12 = deferred_dataref("sim/custom/lights/water_level_12_new", "number")
water_level_14 = deferred_dataref("sim/custom/lights/water_level_14_new", "number")
water_level_0 = deferred_dataref("sim/custom/lights/water_level_0_new", "number")
gears_red_left_eng = deferred_dataref("sim/custom/lights/gears_red_left_eng_new", "number")
gears_red_front_eng = deferred_dataref("sim/custom/lights/gears_red_front_eng_new", "number")
gears_red_right_eng = deferred_dataref("sim/custom/lights/gears_red_right_eng_new", "number")
gears_green_left_eng = deferred_dataref("sim/custom/lights/gears_green_left_eng_new", "number")
gears_green_front_eng = deferred_dataref("sim/custom/lights/gears_green_front_eng_new", "number")
gears_green_right_eng = deferred_dataref("sim/custom/lights/gears_green_right_eng_new", "number")
eng2_fuel_p = deferred_dataref("sim/custom/lights/engines/eng2_fuel_p_new", "number")
transponder1_fail = deferred_dataref("sim/custom/lights/small/transponder1_fail_new", "number")
transponder1_kd = deferred_dataref("sim/custom/lights/small/transponder1_kd_new", "number")
transponder1_kp = deferred_dataref("sim/custom/lights/small/transponder1_kp_new", "number")
leftside_yellow = deferred_dataref("sim/custom/lights/small/leftside_yellow_new", "number")
front_hydr_fail_1 = deferred_dataref("sim/custom/lights/small/front_hydr_fail_1_new", "number")
front_hydr_fail_2 = deferred_dataref("sim/custom/lights/small/front_hydr_fail_2_new", "number")
front_hydr_fail_3 = deferred_dataref("sim/custom/lights/small/front_hydr_fail_3_new", "number")
front_hydr_fail_4 = deferred_dataref("sim/custom/lights/small/front_hydr_fail_4_new", "number")
stu_roll = deferred_dataref("sim/custom/lights/small/stu_roll_new", "number")
stu_pitch = deferred_dataref("sim/custom/lights/small/stu_pitch_new", "number")
stu_toga = deferred_dataref("sim/custom/lights/small/stu_toga_new", "number")
at_2 = deferred_dataref("sim/custom/lights/small/at_2_new", "number")
at_1 = deferred_dataref("sim/custom/lights/small/at_1_new", "number")
nav_1_to = deferred_dataref("sim/custom/lights/small/nav_1_to_new", "number")
nav_1_from = deferred_dataref("sim/custom/lights/small/nav_1_from_new", "number")
nav_2_to = deferred_dataref("sim/custom/lights/small/nav_2_to_new", "number")
nav_2_from = deferred_dataref("sim/custom/lights/small/nav_2_from_new", "number")
bkk_ok = deferred_dataref("sim/custom/lights/small/bkk_ok_new", "number")
heat_ok_1 = deferred_dataref("sim/custom/lights/small/heat_ok_1_new", "number")
heat_ok_2 = deferred_dataref("sim/custom/lights/small/heat_ok_2_new", "number")
heat_ok_3 = deferred_dataref("sim/custom/lights/small/heat_ok_3_new", "number")
left_bus_on_tr2 = deferred_dataref("sim/custom/lights/small/left_bus_on_tr2_new", "number")
right_bus_on_tr1 = deferred_dataref("sim/custom/lights/small/right_bus_on_tr1_new", "number")
pts250_n1 = deferred_dataref("sim/custom/lights/small/pts250_n1_new", "number")
pts250_n2 = deferred_dataref("sim/custom/lights/small/pts250_n2_new", "number")
vu_on_1 = deferred_dataref("sim/custom/lights/small/vu_on_1_new", "number")
turn_off_bat_1 = deferred_dataref("sim/custom/lights/small/turn_off_bat_1_new", "number")
left_bus_use_bat = deferred_dataref("sim/custom/lights/small/left_bus_use_bat_new", "number")
turn_off_bat_3 = deferred_dataref("sim/custom/lights/small/turn_off_bat_3_new", "number")
vu_on_2 = deferred_dataref("sim/custom/lights/small/vu_on_2_new", "number")
turn_off_bat_2 = deferred_dataref("sim/custom/lights/small/turn_off_bat_2_new", "number")
right_bus_use_bat = deferred_dataref("sim/custom/lights/small/right_bus_use_bat_new", "number")
skv_overpress_left = deferred_dataref("sim/custom/lights/small/skv_overpress_left_new", "number")
skv_overpress_right = deferred_dataref("sim/custom/lights/small/skv_overpress_right_new", "number")
skv_bleed_fail_1 = deferred_dataref("sim/custom/lights/small/skv_bleed_fail_1_new", "number")
skv_bleed_fail_2 = deferred_dataref("sim/custom/lights/small/skv_bleed_fail_2_new", "number")
skv_bleed_fail_3 = deferred_dataref("sim/custom/lights/small/skv_bleed_fail_3_new", "number")
skv_tail_temp = deferred_dataref("sim/custom/lights/small/skv_tail_temp_new", "number")
skv_bleed_closed_1 = deferred_dataref("sim/custom/lights/small/skv_bleed_closed_1_new", "number")
skv_bleed_closed_2 = deferred_dataref("sim/custom/lights/small/skv_bleed_closed_2_new", "number")
skv_bleed_closed_3 = deferred_dataref("sim/custom/lights/small/skv_bleed_closed_3_new", "number")
apd_work_1 = deferred_dataref("sim/custom/lights/small/apd_work_1_new", "number")
apd_work_2 = deferred_dataref("sim/custom/lights/small/apd_work_2_new", "number")
apd_work_3 = deferred_dataref("sim/custom/lights/small/apd_work_3_new", "number")
close_toilet = deferred_dataref("sim/custom/lights/small/close_toilet_new", "number")
srd_low_press = deferred_dataref("sim/custom/lights/small/srd_low_press_new", "number")
srd_overpress = deferred_dataref("sim/custom/lights/small/srd_overpress_new", "number")
soi_ice_detected = deferred_dataref("sim/custom/lights/small/soi_ice_detected_new", "number")
soi_work = deferred_dataref("sim/custom/lights/small/soi_work_new", "number")
tail_temp_high = deferred_dataref("sim/custom/lights/small/tail_temp_high_new", "number")
lavatory_heat = deferred_dataref("sim/custom/lights/small/lavatory_heat_new", "number")
galley_heat = deferred_dataref("sim/custom/lights/small/galley_heat_new", "number")
turn_on_aux = deferred_dataref("sim/custom/lights/small/turn_on_aux_new", "number")
tks_contr_fail = deferred_dataref("sim/custom/lights/small/tks_contr_fail_new", "number")
light_fuel_pump_1 = deferred_dataref("sim/custom/lights/small/fuel_pump_1_new", "number")
light_fuel_pump_2 = deferred_dataref("sim/custom/lights/small/fuel_pump_2_new", "number")
light_fuel_pump_3 = deferred_dataref("sim/custom/lights/small/fuel_pump_3_new", "number")
light_fuel_pump_4 = deferred_dataref("sim/custom/lights/small/fuel_pump_4_new", "number")
light_fuel_pump_10 = deferred_dataref("sim/custom/lights/small/fuel_pump_10_new", "number")
light_fuel_pump_11 = deferred_dataref("sim/custom/lights/small/fuel_pump_11_new", "number")
light_fuel_pump_left_5 = deferred_dataref("sim/custom/lights/small/fuel_pump_left_5_new", "number")
light_fuel_pump_left_6 = deferred_dataref("sim/custom/lights/small/fuel_pump_left_6_new", "number")
light_fuel_pump_left_7 = deferred_dataref("sim/custom/lights/small/fuel_pump_left_7_new", "number")
light_fuel_pump_left_8 = deferred_dataref("sim/custom/lights/small/fuel_pump_left_8_new", "number")
light_fuel_pump_left_9 = deferred_dataref("sim/custom/lights/small/fuel_pump_left_9_new", "number")
light_fuel_pump_right_5 = deferred_dataref("sim/custom/lights/small/fuel_pump_right_5_new", "number")
light_fuel_pump_right_6 = deferred_dataref("sim/custom/lights/small/fuel_pump_right_6_new", "number")
light_fuel_pump_right_7 = deferred_dataref("sim/custom/lights/small/fuel_pump_right_7_new", "number")
light_fuel_pump_right_8 = deferred_dataref("sim/custom/lights/small/fuel_pump_right_8_new", "number")
light_fuel_pump_right_9 = deferred_dataref("sim/custom/lights/small/fuel_pump_right_9_new", "number")



turn_off_bat_4 = deferred_dataref("sim/custom/lights/small/turn_off_bat_4_new", "number")
bus_connected = deferred_dataref("sim/custom/lights/small/bus_connected_new", "number")
emerg_inv_115 = deferred_dataref("sim/custom/lights/small/emerg_inv_115_new", "number")
bus_npk_1 = deferred_dataref("sim/custom/lights/small/bus_npk_1_new", "number")
bus_npk_2 = deferred_dataref("sim/custom/lights/small/bus_npk_2_new", "number")
apu_gen_on2 = deferred_dataref("sim/custom/lights/small/apu_gen_on_new2", "number")
fuel_2500 = deferred_dataref("sim/custom/lights/small/fuel_2500_new", "number")
starter_high_rpm_1 = deferred_dataref("sim/custom/lights/small/starter_high_rpm_1_new", "number")
starter_high_rpm_2 = deferred_dataref("sim/custom/lights/small/starter_high_rpm_2_new", "number")
fuel_tank1_used = deferred_dataref("sim/custom/lights/small/fuel_tank1_used_new", "number")
starter_high_rpm_3 = deferred_dataref("sim/custom/lights/small/starter_high_rpm_3_new", "number")

fuel_flow_auto_fail = deferred_dataref("sim/custom/lights/small/fuel_flow_auto_fail_new", "number")
fuel_cut_off_1 = deferred_dataref("sim/custom/lights/small/fuel_cut_off_1_new", "number")
fuel_cut_off_2 = deferred_dataref("sim/custom/lights/small/fuel_cut_off_2_new", "number")
fuel_cut_off_3 = deferred_dataref("sim/custom/lights/small/fuel_cut_off_3_new", "number")
fuel_level_automat = deferred_dataref("sim/custom/lights/small/fuel_level_automat_new", "number")
skv_overheat = deferred_dataref("sim/custom/lights/small/skv_overheat_new", "number")
eng_hydr_fail_1 = deferred_dataref("sim/custom/lights/small/eng_hydr_fail_1_new", "number")
eng_hydr_fail_2 = deferred_dataref("sim/custom/lights/small/eng_hydr_fail_2_new", "number")
eng_hydr_fail_3 = deferred_dataref("sim/custom/lights/small/eng_hydr_fail_3_new", "number")
eng_hydr_fail_4 = deferred_dataref("sim/custom/lights/small/eng_hydr_fail_4_new", "number")








----- caps slow
simDR_heat_close_cap = find_dataref("tu154b2/custom/switchers/airbleed/heat_close_cap")
simDR_eject = find_dataref("sim/custom/b2/airflow_eject_cap")
simDR_sbk1 = find_dataref("tu154b2/custom/switchers/ovhd/sp50_dme_rsbn")
simDR_sbk2 = find_dataref("tu154b2/custom/switchers/eng/hydro_trimm_rud_1_cap")
simDR_parking_brake = find_dataref("tu154b2/custom/controll/parking_brake")
simDR_vu_res_test_cap = find_dataref("sim/custom/gauges/elec/vu_res_test_cap")
simDR_nosewheel_turn_cap = find_dataref("tu154b2/custom/switchers/nosewheel_turn_cap")
simDR_eng_light_angle2 = find_dataref("sim/custom/eng_light_angle2")
simDR_flaps_sel_cap = find_dataref("tu154b2/custom/switchers/flaps_sel_cap")
simDR_gears_retr_lock_cap = find_dataref("tu154b2/custom/switchers/gears_retr_lock_cap")
simDR_gears_ext_3GS_cap = find_dataref("tu154b2/custom/switchers/gears_ext_3GS_cap")
simDR_stab_man_cap = find_dataref("tu154b2/custom/controll/stab_man_cap")
simDR_contr_force_cap = find_dataref("tu154b2/custom/controll/contr_force_cap")
simDR_bkk_contr_cap = find_dataref("tu154b2/custom/switchers/ovhd/bkk_contr_cap")
simDR_bkk_on_cap = find_dataref("tu154b2/custom/switchers/ovhd/bkk_on_cap")
simDR_sau_stu_cap = find_dataref("tu154b2/custom/switchers/ovhd/sau_stu_cap")
simDR_pkp_left_cap = find_dataref("tu154b2/custom/switchers/ovhd/pkp_left_cap")
simDR_pkp_right_cap = find_dataref("tu154b2/custom/switchers/ovhd/pkp_right_cap")
simDR_mgv_contr_cap = find_dataref("tu154b2/custom/switchers/ovhd/mgv_contr_cap")
simDR_absu_speed_off_cap = find_dataref("tu154b2/custom/switchers/console/absu_speed_off_cap")
simDR_absu_smooth_on_cap = find_dataref("tu154b2/custom/switchers/console/absu_smooth_on_cap")
simDR_absu_arrest_cap = find_dataref("tu154b2/custom/buttons/console/absu_arrest_cap")
simDR_emerg_elev_trimm_cap = find_dataref("tu154b2/custom/switchers/console/emerg_elev_trimm_cap")
simDR_absu_speed_prepare_cap = find_dataref("tu154b2/custom/switchers/console/absu_speed_prepare_cap")
simDR_landing_light_off_cap = find_dataref("tu154b2/custom/lights/landing_light_off_cap")
simDR_srd_buzzer_cap = find_dataref("tu154b2/custom/switchers/eng/srd_buzzer_cap")
simDR_fuel_buzzer_cap = find_dataref("tu154b2/custom/switchers/eng/fuel_buzzer_cap")
simDR_emerg_inv115_cap = find_dataref("tu154b2/custom/switchers/eng/emerg_inv115_cap")
simDR_pts250_mode_cap = find_dataref("tu154b2/custom/switchers/eng/pts250_mode_cap")
simDR_pts250_on_cap = find_dataref("tu154b2/custom/switchers/eng/pts250_on_cap")
simDR_fuel_porc_cap = find_dataref("tu154b2/custom/switchers/fuel/fuel_porc_cap")
simDR_fuel_trans_cap = find_dataref("tu154b2/custom/switchers/fuel/fuel_trans_cap")
simDR_fuel_flow_on_cap = find_dataref("tu154b2/custom/switchers/fuel/fuel_flow_on_cap")
simDR_fire_valve_1_cap = find_dataref("tu154b2/custom/switchers/fuel/fire_valve_1_cap")
simDR_fire_valve_2_cap = find_dataref("tu154b2/custom/switchers/fuel/fire_valve_2_cap")
simDR_fire_valve_3_cap = find_dataref("tu154b2/custom/switchers/fuel/fire_valve_3_cap")
simDR_apu_fire_crane_cap = find_dataref("sim/custom/b2/apu_fire_crane_cap")
simDR_connect2to1_cap = find_dataref("tu154b2/custom/switchers/hydro/connect2to1_cap")
simDR_psvp_left_on_cap = find_dataref("tu154b2/custom/switchers/airbleed/psvp_left_on_cap")
simDR_psvp_right_on_cap = find_dataref("tu154b2/custom/switchers/airbleed/psvp_right_on_cap")
simDR_emerg_decompress_cap = find_dataref("tu154b2/custom/switchers/airbleed/emerg_decompress_cap")
simDR_starter_cap = find_dataref("tu154b2/custom/switchers/eng/starter_cap")
simDR_sard_disable_cap = find_dataref("tu154b2/custom/switchers/eng/sard_disable_cap")
simDR_hydro_circuit_auto_man_cap = find_dataref("tu154b2/custom/switchers/eng/hydro_circuit_auto_man_cap")
simDR_hydro_long_control_cap = find_dataref("tu154b2/custom/switchers/eng/hydro_long_control_cap")
simDR_gen_3_bus_auto_cap = find_dataref("sim/custom/elec/gen_3_bus_auto_cap")
simDR_gen_2_bus_auto_cap = find_dataref("sim/custom/elec/gen_2_bus_auto_cap")
simDR_gen_1_bus_auto_cap = find_dataref("sim/custom/elec/gen_1_bus_auto_cap")
simDR_transponder_emerg_cap = find_dataref("tu154b2/custom/buttons/ovhd/transponder_emerg_cap")
simDR_elev_trimm_2_pk_cap = find_dataref("sim/custom/b2/elev_trimm_2_pk_cap")
simDR_elev_trimm_1_pk_cap = find_dataref("sim/custom/b2/elev_trimm_1_pk_cap")
simDR_rt12_1_dis_cap = find_dataref("sim/custom/b2/rt12_1_dis_cap")
simDR_rt12_2_dis_cap = find_dataref("sim/custom/b2/rt12_2_dis_cap")
simDR_rt12_3_dis_cap = find_dataref("sim/custom/b2/rt12_3_dis_cap")
simDR_busters_cap = find_dataref("sim/custom/switchers/console/busters_cap_new")
simDR_flaps_power_cap = find_dataref("sim/custom/b2/flaps_power_cap")
simDR_stp_test_cap = find_dataref("sim/custom/b2/stp_test_cap")
simDR_slat_man_cap = find_dataref("tu154b2/custom/switchers/slat_man_cap")
simDR_sard_dbl_cap = find_dataref("tu154b2/custom/switchers/airbleed/dubler_on_cap")
simDR_sard_cap1 = find_dataref("sim/custom/switchers/sard/sard_pribor_cap1")
simDR_sard_cap2 = find_dataref("sim/custom/switchers/sard/sard_pribor_cap2")
simDR_refuel_panel_cap = find_dataref("sim/custom/t154gnd/refuel_panel_cap")





refuel_panel_cap = deferred_dataref("sim/custom/t154gnd/refuel_panel_cap_anim", "number")
sard_cap1 = deferred_dataref("sim/custom/switchers/sard/sard_pribor_cap1_new", "number")
sard_cap2 = deferred_dataref("sim/custom/switchers/sard/sard_pribor_cap2_new", "number")
sard_dbl_cap = deferred_dataref("sim/custom/switchers/airbleed/dubler_on_cap_new", "number")
heat_close_cap = deferred_dataref("sim/custom/switchers/airbleed/heat_close_cap_new", "number")
eject = deferred_dataref("sim/custom/b2/airflow_eject_cap_new", "number")
sbk1 = deferred_dataref("sim/custom/switchers/ovhd/sp50_dme_rsbn_new", "number")
sbk2 = deferred_dataref("sim/custom/switchers/eng/hydro_trimm_rud_1_cap_new", "number")
parking_brake = deferred_dataref("sim/custom/controll/parking_brake_new", "number")
slat_man_cap = deferred_dataref("sim/custom/switchers/slat_man_cap_new", "number")
stp_test_cap = deferred_dataref("sim/custom/b2/stp_test_cap_new", "number")
flaps_power_cap = deferred_dataref("sim/custom/b2/flaps_power_cap_new", "number")
vu_res_test_cap = deferred_dataref("sim/custom/gauges/elec/vu_res_test_cap_new", "number")
nosewheel_turn_cap = deferred_dataref("sim/custom/switchers/nosewheel_turn_cap_new", "number")
eng_light_angle2 = deferred_dataref("sim/custom/eng_light_angle2_new", "number")
busters_cap = deferred_dataref("sim/custom/switchers/console/busters_cap_neww", "number")
flaps_sel_cap = deferred_dataref("sim/custom/switchers/flaps_sel_cap_new", "number")
gears_retr_lock_cap = deferred_dataref("sim/custom/switchers/gears_retr_lock_cap_new", "number")
gears_ext_3GS_cap = deferred_dataref("sim/custom/switchers/gears_ext_3GS_cap_new", "number")
stab_man_cap = deferred_dataref("sim/custom/controll/stab_man_cap_new", "number")
contr_force_cap = deferred_dataref("sim/custom/controll/contr_force_cap_new", "number")
bkk_contr_cap = deferred_dataref("sim/custom/switchers/ovhd/bkk_contr_cap_new", "number")
bkk_on_cap = deferred_dataref("sim/custom/switchers/ovhd/bkk_on_cap_new", "number")
sau_stu_cap = deferred_dataref("sim/custom/switchers/ovhd/sau_stu_cap_new", "number")
pkp_left_cap = deferred_dataref("sim/custom/switchers/ovhd/pkp_left_cap_new", "number")
pkp_right_cap = deferred_dataref("sim/custom/switchers/ovhd/pkp_right_cap_new", "number")
mgv_contr_cap = deferred_dataref("sim/custom/switchers/ovhd/mgv_contr_cap_new", "number")
absu_speed_off_cap = deferred_dataref("sim/custom/switchers/console/absu_speed_off_cap_new", "number")
absu_smooth_on_cap = deferred_dataref("sim/custom/switchers/console/absu_smooth_on_cap_new", "number")
absu_arrest_cap = deferred_dataref("sim/custom/buttons/console/absu_arrest_cap_new", "number")
emerg_elev_trimm_cap = deferred_dataref("sim/custom/switchers/console/emerg_elev_trimm_cap_new", "number")
absu_speed_prepare_cap = deferred_dataref("sim/custom/switchers/console/absu_speed_prepare_cap_new", "number")
landing_light_off_cap = deferred_dataref("sim/custom/lights/landing_light_off_cap_new", "number")
srd_buzzer_cap = deferred_dataref("sim/custom/switchers/eng/srd_buzzer_cap_new", "number")
fuel_buzzer_cap = deferred_dataref("sim/custom/switchers/eng/fuel_buzzer_cap_new", "number")
emerg_inv115_cap = deferred_dataref("sim/custom/switchers/eng/emerg_inv115_cap_new", "number")
pts250_mode_cap = deferred_dataref("sim/custom/switchers/eng/pts250_mode_cap_new", "number")
pts250_on_cap = deferred_dataref("sim/custom/switchers/eng/pts250_on_cap_new", "number")
fuel_porc_cap = deferred_dataref("sim/custom/switchers/fuel/fuel_porc_cap_new", "number")
fuel_trans_cap = deferred_dataref("sim/custom/switchers/fuel/fuel_trans_cap_new", "number")
fuel_flow_on_cap = deferred_dataref("sim/custom/switchers/fuel/fuel_flow_on_cap_new", "number")
fire_valve_1_cap = deferred_dataref("sim/custom/switchers/fuel/fire_valve_1_cap_new", "number")
fire_valve_2_cap = deferred_dataref("sim/custom/switchers/fuel/fire_valve_2_cap_new", "number")
fire_valve_3_cap = deferred_dataref("sim/custom/switchers/fuel/fire_valve_3_cap_new", "number")
apu_fire_crane_cap = deferred_dataref("sim/custom/b2/apu_fire_crane_cap_new", "number")
connect2to1_cap = deferred_dataref("sim/custom/switchers/hydro/connect2to1_cap_new", "number")
psvp_left_on_cap = deferred_dataref("sim/custom/switchers/airbleed/psvp_left_on_cap_new", "number")
psvp_right_on_cap = deferred_dataref("sim/custom/switchers/airbleed/psvp_right_on_cap_new", "number")
emerg_decompress_cap = deferred_dataref("sim/custom/switchers/airbleed/emerg_decompress_cap_new", "number")
starter_cap = deferred_dataref("sim/custom/switchers/eng/starter_cap_new", "number")
sard_disable_cap = deferred_dataref("sim/custom/switchers/eng/sard_disable_cap_new", "number")
hydro_circuit_auto_man_cap = deferred_dataref("sim/custom/switchers/eng/hydro_circuit_auto_man_cap_new", "number")
hydro_long_control_cap = deferred_dataref("sim/custom/switchers/eng/hydro_long_control_cap_new", "number")
gen_3_bus_auto_cap = deferred_dataref("sim/custom/elec/gen_3_bus_auto_cap_new", "number")
gen_2_bus_auto_cap = deferred_dataref("sim/custom/elec/gen_2_bus_auto_cap_new", "number")
gen_1_bus_auto_cap = deferred_dataref("sim/custom/elec/gen_1_bus_auto_cap_new", "number")
transponder_emerg_cap = deferred_dataref("sim/custom/buttons/ovhd/transponder_emerg_cap_new", "number")
elev_trimm_2_pk_cap = deferred_dataref("sim/custom/b2/elev_trimm_2_pk_cap_new", "number")
elev_trimm_1_pk_cap = deferred_dataref("sim/custom/b2/elev_trimm_1_pk_cap_new", "number")
rt12_1_dis_cap = deferred_dataref("sim/custom/b2/rt12_1_dis_cap_new", "number")
rt12_2_dis_cap = deferred_dataref("sim/custom/b2/rt12_2_dis_cap_new", "number")
rt12_3_dis_cap = deferred_dataref("sim/custom/b2/rt12_3_dis_cap_new", "number")


simDR_oil_qty_cap = find_dataref("sim/custom/gauges/eng/oil_qty_cap")
oil_qty_cap_anim = deferred_dataref("sim/custom/gauges/eng/oil_qty_cap_anim", "number")

simDR_ppn13_cap = find_dataref("sim/custom/t154/ppn13_cap")
ppn13_cap_anim = deferred_dataref("sim/custom/t154/ppn13_cap_anim", "number")

----

--- fast anim

simDR_ahz_flag_L = find_dataref("tu154b2/custom/gauges/ahz/ahz_flag_L")
simDR_ahz_flag_R = find_dataref("tu154b2/custom/gauges/ahz/ahz_flag_R")


ahz_flag_L = deferred_dataref("sim/custom/gauges/ahz/ahz_flag_L_new", "number")
ahz_flag_R = deferred_dataref("sim/custom/gauges/ahz/ahz_flag_R_new", "number")

---




local fire_switch_loc = 0

function smooth_light2(orig_lit,new_lit)
    if orig_lit < 0.08 and new_lit < 0.08 then
        return 0
    else
        local new_lit_loc = new_lit
        local orig_lit_loc = math.floor(orig_lit * 10)*0.1
        if orig_lit_loc > new_lit_loc and new_lit_loc < 1 then
            new_lit_loc = new_lit_loc + math.random(8,10)*simDR_passed
        elseif orig_lit_loc < 0.08 and new_lit_loc > 0 then
            new_lit_loc = new_lit_loc - math.random(12,14)*simDR_passed
        elseif orig_lit_loc < 0.9 and orig_lit_loc > 0.6 then
            new_lit_loc = orig_lit_loc
        end
        return new_lit_loc
    end
end  

function smooth_light(target, current_value)

    local fps_factor = math.min(1.0, 11*simDR_passed)

    if target >= (1 - 0.001) and current_value >= (1 - 0.01) then
        return 1
    elseif target <= (0 + 0.001) and current_value <= (0 + 0.01) then
       return 0
    else
        return current_value + ((target - current_value) * fps_factor)
    end

end

function smooth_anim(target, current_value)

    local fps_factor = math.min(1.0, 8.5*simDR_passed)

    if target >= (1 - 0.001) and current_value >= (1 - 0.01) then
        return 1
    elseif target <= (0 + 0.001) and current_value <= (0 + 0.01) then
       return 0
    else
        return current_value + ((target - current_value) * fps_factor)
    end

end

function smooth_anim2(target, current_value)

    local fps_factor = math.min(1.0, 5*simDR_passed)

    if target >= (1 - 0.001) and current_value >= (1 - 0.01) then
        return 1
    elseif target <= (0 + 0.001) and current_value <= (0 + 0.01) then
       return 0
    else
        return current_value + ((target - current_value) * fps_factor)
    end

end

function fast_anim(target, current_value)

    local fps_factor = math.min(1.0, 17.5*simDR_passed)

    if target >= (1 - 0.001) and current_value >= (1 - 0.01) then
        return 1
    elseif target <= (0 + 0.001) and current_value <= (0 + 0.01) then
       return 0
    else
        return current_value + ((target - current_value) * fps_factor)
    end

end








function new_lights()


    ----fast_anim

    
    ahz_flag_L = fast_anim(simDR_ahz_flag_L,ahz_flag_L)
    ahz_flag_R = fast_anim(simDR_ahz_flag_R,ahz_flag_R)




    ---caps
    
    
    ppn13_cap_anim = smooth_anim2(simDR_ppn13_cap,ppn13_cap_anim)
    oil_qty_cap_anim = smooth_anim(simDR_oil_qty_cap,oil_qty_cap_anim)
    refuel_panel_cap = smooth_anim(simDR_refuel_panel_cap,refuel_panel_cap)
    sard_cap1 = smooth_anim(simDR_sard_cap1,sard_cap1)
    sard_cap2 = smooth_anim(simDR_sard_cap2,sard_cap2)
    sard_dbl_cap = smooth_anim(simDR_sard_dbl_cap,sard_dbl_cap)
    heat_close_cap = smooth_anim(simDR_heat_close_cap,heat_close_cap)
    eject = smooth_anim(simDR_eject,eject)
    sbk1 = smooth_anim(simDR_sbk1,sbk1)
    sbk2 = smooth_anim(simDR_sbk2,sbk2)
    parking_brake = smooth_anim(simDR_parking_brake,parking_brake)
    slat_man_cap = smooth_anim(simDR_slat_man_cap,slat_man_cap)
    stp_test_cap = smooth_anim2(simDR_stp_test_cap,stp_test_cap)
    flaps_power_cap = smooth_anim(simDR_flaps_power_cap,flaps_power_cap)
    busters_cap = smooth_anim(simDR_busters_cap,busters_cap)
    eng_light_angle2 = smooth_anim(simDR_eng_light_angle2,eng_light_angle2)
    flaps_sel_cap = smooth_anim(simDR_flaps_sel_cap,flaps_sel_cap)
    gears_retr_lock_cap = smooth_anim(simDR_gears_retr_lock_cap,gears_retr_lock_cap)
    gears_ext_3GS_cap = smooth_anim(simDR_gears_ext_3GS_cap,gears_ext_3GS_cap)
    stab_man_cap = smooth_anim(simDR_stab_man_cap,stab_man_cap)
    contr_force_cap = smooth_anim(simDR_contr_force_cap,contr_force_cap)
    bkk_contr_cap = smooth_anim(simDR_bkk_contr_cap,bkk_contr_cap)
    bkk_on_cap = smooth_anim(simDR_bkk_on_cap,bkk_on_cap)
    sau_stu_cap = smooth_anim(simDR_sau_stu_cap,sau_stu_cap)
    pkp_left_cap = smooth_anim(simDR_pkp_left_cap,pkp_left_cap)
    pkp_right_cap = smooth_anim(simDR_pkp_right_cap,pkp_right_cap)
    mgv_contr_cap = smooth_anim(simDR_mgv_contr_cap,mgv_contr_cap)
    absu_speed_off_cap = smooth_anim(simDR_absu_speed_off_cap,absu_speed_off_cap)
    absu_smooth_on_cap = smooth_anim(simDR_absu_smooth_on_cap,absu_smooth_on_cap)
    absu_arrest_cap = smooth_anim(simDR_absu_arrest_cap,absu_arrest_cap)
    emerg_elev_trimm_cap = smooth_anim(simDR_emerg_elev_trimm_cap,emerg_elev_trimm_cap)
    absu_speed_prepare_cap = smooth_anim(simDR_absu_speed_prepare_cap,absu_speed_prepare_cap)
    landing_light_off_cap = smooth_anim(simDR_landing_light_off_cap,landing_light_off_cap)
    srd_buzzer_cap = smooth_anim(simDR_srd_buzzer_cap,srd_buzzer_cap)
    fuel_buzzer_cap = smooth_anim(simDR_fuel_buzzer_cap,fuel_buzzer_cap)
    emerg_inv115_cap = smooth_anim(simDR_emerg_inv115_cap,emerg_inv115_cap)
    pts250_mode_cap = smooth_anim(simDR_pts250_mode_cap,pts250_mode_cap)
    pts250_on_cap = smooth_anim(simDR_pts250_on_cap,pts250_on_cap)
    fuel_porc_cap = smooth_anim(simDR_fuel_porc_cap,fuel_porc_cap)
    fuel_trans_cap = smooth_anim(simDR_fuel_trans_cap,fuel_trans_cap)
    fuel_flow_on_cap = smooth_anim(simDR_fuel_flow_on_cap,fuel_flow_on_cap)
    fire_valve_1_cap = smooth_anim(simDR_fire_valve_1_cap,fire_valve_1_cap)
    fire_valve_2_cap = smooth_anim(simDR_fire_valve_2_cap,fire_valve_2_cap)
    fire_valve_3_cap = smooth_anim(simDR_fire_valve_3_cap,fire_valve_3_cap)
    apu_fire_crane_cap = smooth_anim(simDR_apu_fire_crane_cap,apu_fire_crane_cap)
    connect2to1_cap = smooth_anim(simDR_connect2to1_cap,connect2to1_cap)
    psvp_left_on_cap = smooth_anim(simDR_psvp_left_on_cap,psvp_left_on_cap)
    psvp_right_on_cap = smooth_anim(simDR_psvp_right_on_cap,psvp_right_on_cap)
    emerg_decompress_cap = smooth_anim(simDR_emerg_decompress_cap,emerg_decompress_cap)
    starter_cap = smooth_anim(simDR_starter_cap,starter_cap)
    sard_disable_cap = smooth_anim(simDR_sard_disable_cap,sard_disable_cap)
    hydro_circuit_auto_man_cap = smooth_anim(simDR_hydro_circuit_auto_man_cap,hydro_circuit_auto_man_cap)
    hydro_long_control_cap = smooth_anim(simDR_hydro_long_control_cap,hydro_long_control_cap)
    gen_3_bus_auto_cap = smooth_anim(simDR_gen_3_bus_auto_cap,gen_3_bus_auto_cap)
    gen_2_bus_auto_cap = smooth_anim(simDR_gen_2_bus_auto_cap,gen_2_bus_auto_cap)
    gen_1_bus_auto_cap = smooth_anim(simDR_gen_1_bus_auto_cap,gen_1_bus_auto_cap)
    transponder_emerg_cap = smooth_anim(simDR_transponder_emerg_cap,transponder_emerg_cap)
    elev_trimm_2_pk_cap = smooth_anim(simDR_elev_trimm_2_pk_cap,elev_trimm_2_pk_cap)
    elev_trimm_1_pk_cap = smooth_anim(simDR_elev_trimm_1_pk_cap,elev_trimm_1_pk_cap)
    rt12_1_dis_cap = smooth_anim(simDR_rt12_1_dis_cap,rt12_1_dis_cap)
    rt12_2_dis_cap = smooth_anim(simDR_rt12_2_dis_cap,rt12_2_dis_cap)
    rt12_3_dis_cap = smooth_anim(simDR_rt12_3_dis_cap,rt12_3_dis_cap)
    vu_res_test_cap = smooth_anim(simDR_vu_res_test_cap,vu_res_test_cap)
    nosewheel_turn_cap = smooth_anim(simDR_nosewheel_turn_cap,nosewheel_turn_cap)
    ---
    
    
    wpt_lamp = smooth_light(simDR_wpt_lamp,wpt_lamp)
    msg_lamp = smooth_light(simDR_msg_lamp,msg_lamp)
    fire_switch = smooth_light(fire_switch_loc,fire_switch)
    trim_p_light = smooth_light(simDR_trim_p_light,trim_p_light)
    trim_r_light = smooth_light(simDR_trim_r_light,trim_r_light)
    trim_c_light = smooth_light(simDR_trim_c_light,trim_c_light)
    toga =  smooth_light(simDR_toga,toga)
    decision_height =  smooth_light(simDR_decision_height,decision_height)
    roll_right_high =  smooth_light(simDR_roll_right_high,roll_right_high)
    pull_up =  smooth_light(simDR_pull_up,pull_up)
    wrong_trimm =  smooth_light(simDR_wrong_trimm,wrong_trimm)
    controll_roll =  smooth_light(simDR_controll_roll,controll_roll)
    controll_pitch =  smooth_light(simDR_controll_pitch,controll_pitch)
    yoke_sign =  smooth_light(simDR_yoke_sign,yoke_sign)
    triangle =  smooth_light(simDR_triangle,triangle)
    controll_thrust =  smooth_light(simDR_controll_thrust,controll_thrust)
    course_lim =  smooth_light(simDR_course_lim,course_lim)
    gs_lim =  smooth_light(simDR_gs_lim,gs_lim)
    fire  =  smooth_light(simDR_fire,fire)
    damper_course =  smooth_light(simDR_damper_course,damper_course)
    damper_roll =  smooth_light(simDR_damper_roll,damper_roll)
    damper_pitch =  smooth_light(simDR_damper_pitch,damper_pitch)
    pitch_control_fail =  smooth_light(simDR_pitch_control_fail,pitch_control_fail)
    roll_control_fail =  smooth_light(simDR_roll_control_fail,roll_control_fail)
    no_reserve_c =  smooth_light(simDR_no_reserve_c,no_reserve_c)
    no_reserve_g =  smooth_light(simDR_no_reserve_g,no_reserve_g)
    ga_main_fail =  smooth_light(simDR_ga_main_fail,ga_main_fail)
    ga_reserve_fail =  smooth_light(simDR_ga_reserve_fail,ga_reserve_fail)
    gs_low =  smooth_light(simDR_gs_low,gs_low)
    srpbz_fail =  smooth_light(simDR_srpbz_fail,srpbz_fail)
    warning_terrain =  smooth_light(simDR_warning_terrain,warning_terrain)
    azimuth_autonom =  smooth_light(simDR_azimuth_autonom,azimuth_autonom)
    change_ch_o =  smooth_light(simDR_change_ch_o,change_ch_o)
    diss_memory =  smooth_light(simDR_diss_memory,diss_memory)
    correct_on =  smooth_light(simDR_correct_on,correct_on)
    dist_autonom =  smooth_light(simDR_dist_autonom,dist_autonom)
    nvu_vor_automat =  smooth_light(simDR_nvu_vor_automat,nvu_vor_automat)
    mgv_control_fail =  smooth_light(simDR_mgv_control_fail,mgv_control_fail)
    nvu_fail =  smooth_light(simDR_nvu_fail,nvu_fail)
    stuard_call =  smooth_light(simDR_stuard_call,stuard_call)
    cockpit_p_low =  smooth_light(simDR_cockpit_p_low,cockpit_p_low)
    fp_eng_fail_1 =  smooth_light(simDR_fp_eng_fail_1,fp_eng_fail_1)
    fp_reverse_1 =  smooth_light(simDR_fp_reverse_1,fp_reverse_1)
    fp_eng_fail_2 =  smooth_light(simDR_fp_eng_fail_2,fp_eng_fail_2)
    fp_eng_fail_3 =  smooth_light(simDR_fp_eng_fail_3,fp_eng_fail_3)
    fp_reverse_3 =  smooth_light(simDR_fp_reverse_3,fp_reverse_3)
    flaps_1_valve =  smooth_light(simDR_flaps_1_valve,flaps_1_valve)
    flaps_2_valve =  smooth_light(simDR_flaps_2_valve,flaps_2_valve)
    spoilers_mid_left =  smooth_light(simDR_spoilers_mid_left,spoilers_mid_left)
    spoilers_inn_left =  smooth_light(simDR_spoilers_inn_left,spoilers_inn_left)
    spoilers_inn_right =  smooth_light(simDR_spoilers_inn_right,spoilers_inn_right)
    spoilers_mid_right =  smooth_light(simDR_spoilers_mid_right,spoilers_mid_right)
    flaps_unsync =  smooth_light(simDR_flaps_unsync,flaps_unsync)
    slats_unsync =  smooth_light(simDR_slats_unsync,slats_unsync)
    gears_green_left =  smooth_light(simDR_gears_green_left,gears_green_left)
    gears_green_front =  smooth_light(simDR_gears_green_front,gears_green_front)
    gears_green_right =  smooth_light(simDR_gears_green_right,gears_green_right)
    gears_red_left =  smooth_light(simDR_gears_red_left,gears_red_left)
    gears_red_front =  smooth_light(simDR_gears_red_front,gears_red_front)
    gears_red_right =  smooth_light(simDR_gears_red_right,gears_red_right)
    gears_not_ext =  smooth_light(simDR_gears_not_ext,gears_not_ext)
    alpha_high =  smooth_light(simDR_alpha_high,alpha_high)
    g_force_high =  smooth_light(simDR_g_force_high,g_force_high)
    fuel_flow_from_4 = smooth_light(simDR_fuel_flow_from_4,fuel_flow_from_4)
    fuel_flow_from_2 = smooth_light(simDR_fuel_flow_from_2,fuel_flow_from_2)
    fuel_porc_reserv = smooth_light(simDR_fuel_porc_reserv,fuel_porc_reserv)
    fuel_flow_from_3 = smooth_light(simDR_fuel_flow_from_3,fuel_flow_from_3)
    fuel_tank2_right_fail = smooth_light(simDR_light_fuel_pump_right_2_fail,fuel_tank2_right_fail)
    fuel_tank2_left_fail = smooth_light(simDR_light_fuel_pump_left_2_fail,fuel_tank2_left_fail)
    fuel_tank3_left_fail = smooth_light(simDR_light_fuel_pump_left_3_fail,fuel_tank3_left_fail)
    fuel_tank3_right_fail = smooth_light(simDR_light_fuel_pump_right_3_fail,fuel_tank3_right_fail)
    fuel_reserv_trans_left = smooth_light(simDR_fuel_reserv_trans_left,fuel_reserv_trans_left)
    fuel_reserv_trans_right = smooth_light(simDR_fuel_reserv_trans_right,fuel_reserv_trans_right)
    msrp_mars = smooth_light(simDR_msrp_mars,msrp_mars)
    msrp_up2 = smooth_light(simDR_msrp_up2,msrp_up2)
    msrp_mlp_aux = smooth_light(simDR_msrp_mlp_aux,msrp_mlp_aux)
    msrp_mlp_main = smooth_light(simDR_msrp_mlp_main,msrp_mlp_main)
    antiice_wings = smooth_light(simDR_antiice_wings,antiice_wings)
    antiice_eng_3 = smooth_light(simDR_antiice_eng_3,antiice_eng_3)
    antiice_eng_2 = smooth_light(simDR_antiice_eng_2,antiice_eng_2)
    antiice_slats = smooth_light(simDR_antiice_slats,antiice_slats)
    antiice_eng_1 = smooth_light(simDR_antiice_eng_1,antiice_eng_1) 
    vd15_lamp = smooth_light(simDR_vd15_lamp,vd15_lamp)
    absu_work = smooth_light(simDR_absu_work,absu_work)
    tks_main_fail = smooth_light(simDR_tks_main_fail,tks_main_fail)
    auasp_lamp = smooth_light(simDR_auasp_lamp,auasp_lamp)
    exit_lamp = smooth_light(simDR_exit_lamp,exit_lamp)
    pnp_rsbn_left = smooth_light(simDR_pnp_rsbn_left,pnp_rsbn_left)
    pnp_sp_left = smooth_light(simDR_pnp_sp_left,pnp_sp_left)
    pnp_vor_left = smooth_light(simDR_pnp_vor_left,pnp_vor_left)
    pnp_nv_left = smooth_light(simDR_pnp_nv_left,pnp_nv_left)
    pnp_nv_right = smooth_light(simDR_pnp_nv_right,pnp_nv_right)
    pnp_vor_right = smooth_light(simDR_pnp_vor_right,pnp_vor_right)
    pnp_sp_right = smooth_light(simDR_pnp_sp_right,pnp_sp_right)
    pnp_rsbn_right = smooth_light(simDR_pnp_rsbn_right,pnp_rsbn_right)
    sp50_c1 = smooth_light(simDR_sp50_c1,sp50_c1)
    sp50_g1 = smooth_light(simDR_sp50_g1,sp50_g1)
    sp50_g2 = smooth_light(simDR_sp50_g2,sp50_g2)
    sp50_c2 = smooth_light(simDR_sp50_c2,sp50_c2)
    transponder_green = smooth_light(simDR_transponder_green,transponder_green)
    dme_km_left = smooth_light(simDR_dme_km_left,dme_km_left)
    dme_mile_left = smooth_light(simDR_dme_mile_left,dme_mile_left)
    dme_km_right = smooth_light(simDR_dme_km_right,dme_km_right)
    dme_mile_right = smooth_light(simDR_dme_mile_right,dme_mile_right)
    oil_meter_1 = smooth_light(simDR_oil_meter_1,oil_meter_1)
    oil_meter_2 = smooth_light(simDR_oil_meter_2,oil_meter_2)
    oil_meter_3 = smooth_light(simDR_oil_meter_3,oil_meter_3)
    marker_2 =  smooth_light(simDR_marker_2,marker_2)
    marker_3 =  smooth_light(simDR_marker_3,marker_3)
    marker_1 =  smooth_light(simDR_marker_1,marker_1)
    stab_m = smooth_light(simDR_stab_m,stab_m)
    vor_lamp =  smooth_light(simDR_vor_lamp,vor_lamp)
    stab_v =  smooth_light(simDR_stab_v,stab_v)
    nvu_lamp =  smooth_light(simDR_nvu_lamp,nvu_lamp)
    stab_h =  smooth_light(simDR_stab_h,stab_h)
    stab_roll =  smooth_light(simDR_stab_roll,stab_roll)
    stab_pitch =  smooth_light(simDR_stab_pitch,stab_pitch)
    zk_lamp =  smooth_light(simDR_zk_lamp,zk_lamp)
    thrust_automat =  smooth_light(simDR_thrust_automat,thrust_automat)
    course =  smooth_light(simDR_course,course)
    glideslope =  smooth_light(simDR_glideslope,glideslope)
    no_ag_controll =  smooth_light(simDR_no_ag_controll,no_ag_controll)
    sns_lamp =  smooth_light(simDR_sns_lamp,sns_lamp)
    speed_high =  smooth_light(simDR_speed_high,speed_high)
    check_alt_left =  smooth_light(simDR_check_alt_left,check_alt_left)
    check_alt_right =  smooth_light(simDR_check_alt_right,check_alt_right)
    sso_connect =  smooth_light(simDR_sso_connect,sso_connect)
    ofuel_less_2500 =  smooth_light(simDR_ofuel_less_2500,ofuel_less_2500)
    sso_danger =  smooth_light(simDR_sso_danger,sso_danger)
    roll_left_high =  smooth_light(simDR_roll_left_high,roll_left_high)
    pta6_fail = smooth_light(simDR_pta6_fail,pta6_fail)
    start_apu = smooth_light(simDR_start_apu,start_apu)
    high_rpm = smooth_light(simDR_high_rpm,high_rpm)
    high_temp = smooth_light(simDR_high_temp,high_temp)
    work_mode = smooth_light(simDR_work_mode,work_mode)
    start_ready = smooth_light(simDR_start_ready,start_ready)
    low_oil_press = smooth_light(simDR_low_oil_press,low_oil_press)
    fuel_press = smooth_light(simDR_fuel_press,fuel_press)
    low_oil = smooth_light(simDR_low_oil,low_oil)
    doors_open = smooth_light(simDR_doors_open,doors_open)
    eng1_reverse_lock = smooth_light(simDR_eng1_reverse_lock,eng1_reverse_lock)
    eng1_reverse_doors = smooth_light(simDR_eng1_reverse_doors,eng1_reverse_doors)
    eng1_vna33 = smooth_light(simDR_eng1_vna33,eng1_vna33)
    eng1_vna0 = smooth_light(simDR_eng1_vna0,eng1_vna0)
    eng1_bypass_valve = smooth_light(simDR_eng1_bypass_valve,eng1_bypass_valve)
    eng1_filter_fail = smooth_light(simDR_eng1_filter_fail,eng1_filter_fail)
    eng1_oil_p = smooth_light(simDR_eng1_oil_p,eng1_oil_p)
    eng1_fuel_p = smooth_light(simDR_eng1_fuel_p,eng1_fuel_p)
    eng1_oil_level = smooth_light(simDR_eng1_oil_level,eng1_oil_level)
    eng1_chips = smooth_light(simDR_eng1_chips,eng1_chips)
	eng1_t = smooth_light(simDR_eng1_t_high,eng1_t)
	eng1_stop = smooth_light(simDR_eng1_stop,eng1_stop)
    eng1_dangerous_vibro = smooth_light(simDR_eng1_dangerous_vibro,eng1_dangerous_vibro)
    eng1_high_vibro = smooth_light(simDR_eng1_high_vibro,eng1_high_vibro)
    eng2_dangerous_vibro = smooth_light(simDR_eng2_dangerous_vibro,eng2_dangerous_vibro)
    eng2_high_vibro = smooth_light(simDR_eng2_high_vibro,eng2_high_vibro)
    eng2_oil_level = smooth_light(simDR_eng2_oil_level,eng2_oil_level)
    eng2_chips = smooth_light(simDR_eng2_chips,eng2_chips)
	eng2_t = smooth_light(simDR_eng2_t_high,eng2_t)
	eng2_stop = smooth_light(simDR_eng2_stop,eng2_stop)
    eng2_oil_p = smooth_light(simDR_eng2_oil_p,eng2_oil_p)
    eng2_bypass_valve = smooth_light(simDR_eng2_bypass_valve,eng2_bypass_valve)
    eng2_filter_fail = smooth_light(simDR_eng2_filter_fail,eng2_filter_fail)
    eng2_vna33 = smooth_light(simDR_eng2_vna33,eng2_vna33)
    eng2_vna0 = smooth_light(simDR_eng2_vna0,eng2_vna0)
    eng_at_on = smooth_light(simDR_eng_at_on,eng_at_on)
    eng_block = smooth_light(simDR_eng_block,eng_block)
    eng3_dangerous_vibro = smooth_light(simDR_eng3_dangerous_vibro,eng3_dangerous_vibro)
    eng3_high_vibro = smooth_light(simDR_eng3_high_vibro,eng3_high_vibro)
    eng3_oil_level= smooth_light(simDR_eng3_oil_level,eng3_oil_level)
    eng3_chips = smooth_light(simDR_eng3_chips,eng3_chips)
	eng3_t = smooth_light(simDR_eng3_t_high,eng3_t)
	eng3_stop = smooth_light(simDR_eng3_stop,eng3_stop)
    eng3_oil_p = smooth_light(simDR_eng3_oil_p,eng3_oil_p)
    eng3_fuel_p = smooth_light(simDR_eng3_fuel_p,eng3_fuel_p)
    eng3_bypass_valve = smooth_light(simDR_eng3_bypass_valve,eng3_bypass_valve)
    eng3_filter_fail = smooth_light(simDR_eng3_filter_fail,eng3_filter_fail)
    eng3_vna33 = smooth_light(simDR_eng3_vna33,eng3_vna33)
    eng3_vna0 = smooth_light(simDR_eng3_vna0,eng3_vna0)
    eng3_reverse_lock = smooth_light(simDR_eng3_reverse_lock,eng3_reverse_lock)
    eng3_reverse_doors = smooth_light(simDR_eng3_reverse_doors,eng3_reverse_doors)
    ra56_pitch_fail_1 = smooth_light(simDR_ra56_pitch_fail_1,ra56_pitch_fail_1)
    ra56_pitch_fail_2 = smooth_light(simDR_ra56_pitch_fail_2,ra56_pitch_fail_2)
    ra56_pitch_fail_3 = smooth_light(simDR_ra56_pitch_fail_3,ra56_pitch_fail_3)
    ra56_roll_fail_1 = smooth_light(simDR_ra56_roll_fail_1,ra56_roll_fail_1)
    ra56_roll_fail_2 = smooth_light(simDR_ra56_roll_fail_2,ra56_roll_fail_2)
    ra56_roll_fail_3 = smooth_light(simDR_ra56_roll_fail_3,ra56_roll_fail_3)
    ra56_course_fail_1 = smooth_light(simDR_ra56_course_fail_1,ra56_course_fail_1)
    ra56_course_fail_2 = smooth_light(simDR_ra56_course_fail_2,ra56_course_fail_2)
    ra56_course_fail_3 = smooth_light(simDR_ra56_course_fail_3,ra56_course_fail_3)
    nvu_no_reserve = smooth_light(simDR_nvu_no_reserve,nvu_no_reserve)
    smoke_1 = smooth_light(simDR_smoke_1,smoke_1)
    smoke_zone2_left = smooth_light(simDR_smoke_zone2_left,smoke_zone2_left)
    smoke_zone3 = smooth_light(simDR_smoke_zone3,smoke_zone3)
    smoke_zone2_right = smooth_light(simDR_smoke_zone2_right,smoke_zone2_right)
    smoke_zone4 = smooth_light(simDR_smoke_zone4,smoke_zone4)
    smoke_2 = smooth_light(simDR_smoke_2,smoke_2)
    smoke_zone5_left = smooth_light(simDR_smoke_zone5_left,smoke_zone5_left)
    smoke_zone5_right = smooth_light(simDR_smoke_zone5_right,smoke_zone5_right)
    smoke_zone6 = smooth_light(simDR_smoke_zone6,smoke_zone6)
    fire_ng = smooth_light(simDR_fire_ng,fire_ng)
    fire_eng_1 = smooth_light(simDR_fire_eng_1,fire_eng_1)
    fire_eng_2 = smooth_light(simDR_fire_eng_2,fire_eng_2)
    fire_eng_3 = smooth_light(simDR_fire_eng_3,fire_eng_3)
    fire_turn_1 = smooth_light(simDR_fire_turn_1,fire_turn_1)
    fire_turn_2 = smooth_light(simDR_fire_turn_2,fire_turn_2)
    fire_turn_3 = smooth_light(simDR_fire_turn_3,fire_turn_3)
    overheat_eng_1 = smooth_light(simDR_overheat_eng_1,overheat_eng_1)
    overheat_eng_2 = smooth_light(simDR_overheat_eng_2,overheat_eng_2)
    overheat_eng_3 = smooth_light(simDR_overheat_eng_3,overheat_eng_3)
    fuel_off_eng_1 = smooth_light(simDR_fuel_off_eng_1,fuel_off_eng_1)
    fuel_off_eng_2 = smooth_light(simDR_fuel_off_eng_2,fuel_off_eng_2)
    fuel_off_eng_3 = smooth_light(simDR_fuel_off_eng_3,fuel_off_eng_3)
    check_overheat = smooth_light(simDR_check_overheat,check_overheat)
    fire_apu = smooth_light(simDR_fire_apu,fire_apu)
    turn_on_spz = smooth_light(simDR_turn_on_spz,turn_on_spz)
    left_front_pax_door = smooth_light(simDR_left_front_pax_door,left_front_pax_door)
    left_mid_pax_door = smooth_light(simDR_left_mid_pax_door,left_mid_pax_door)
    other_hatches = smooth_light(simDR_other_hatches,other_hatches)
    right_mid_pax_door = smooth_light(simDR_right_mid_pax_door,right_mid_pax_door)
    cargo_front_door = smooth_light(simDR_cargo_front_door,cargo_front_door)
    cargo_back_door = smooth_light(simDR_cargo_back_door,cargo_back_door)
    turn63_lamp = smooth_light(simDR_turn63_lamp,turn63_lamp)
    nosewheel_turn_off = smooth_light(simDR_nosewheel_turn_off,nosewheel_turn_off)
    busters_off = smooth_light(simDR_busters_off,busters_off)
    water_level_1 = smooth_light(simDR_water_level_1,water_level_1)
    water_level_12 = smooth_light(simDR_water_level_12,water_level_12)
    water_level_14 = smooth_light(simDR_water_level_14,water_level_14)
    water_level_0 = smooth_light(simDR_water_level_0,water_level_0)
    gears_red_left_eng = smooth_light(simDR_gears_red_left_eng,gears_red_left_eng)
    gears_red_front_eng = smooth_light(simDR_gears_red_front_eng,gears_red_front_eng)
    gears_red_right_eng = smooth_light(simDR_gears_red_right_eng,gears_red_right_eng)
    gears_green_left_eng = smooth_light(simDR_gears_green_left_eng,gears_green_left_eng)
    gears_green_front_eng = smooth_light(simDR_gears_green_front_eng,gears_green_front_eng)
    gears_green_right_eng = smooth_light(simDR_gears_green_right_eng,gears_green_right_eng)
    eng2_fuel_p = smooth_light(simDR_eng2_fuel_p,eng2_fuel_p)
    transponder1_fail = smooth_light(simDR_transponder1_fail,transponder1_fail)
    transponder1_kd = smooth_light(simDR_transponder1_kd,transponder1_kd)
    transponder1_kp = smooth_light(simDR_transponder1_kp,transponder1_kp)
    leftside_yellow = smooth_light(simDR_leftside_yellow,leftside_yellow)
    front_hydr_fail_1 = smooth_light(simDR_front_hydr_fail_1,front_hydr_fail_1)
    front_hydr_fail_2 = smooth_light(simDR_front_hydr_fail_2,front_hydr_fail_2)
    front_hydr_fail_3 = smooth_light(simDR_front_hydr_fail_3,front_hydr_fail_3)
    front_hydr_fail_4 = smooth_light(simDR_front_hydr_fail_4,front_hydr_fail_4)
    stu_roll = smooth_light(simDR_stu_roll,stu_roll)
    stu_pitch = smooth_light(simDR_stu_pitch,stu_pitch)
    stu_toga = smooth_light(simDR_stu_toga,stu_toga)
    at_2 = smooth_light(simDR_at_2,at_2)
    at_1 = smooth_light(simDR_at_1,at_1)
    nav_1_to = smooth_light(simDR_nav_1_to,nav_1_to)
    nav_1_from = smooth_light(simDR_nav_1_from,nav_1_from)
    nav_2_to = smooth_light(simDR_nav_2_to,nav_2_to)
    nav_2_from = smooth_light(simDR_nav_2_from,nav_2_from)
    bkk_ok = smooth_light(simDR_bkk_ok,bkk_ok)
    heat_ok_1 = smooth_light(simDR_heat_ok_1,heat_ok_1)
    heat_ok_2 = smooth_light(simDR_heat_ok_2,heat_ok_2)
    heat_ok_3 = smooth_light(simDR_heat_ok_3,heat_ok_3)
    left_bus_on_tr2 = smooth_light(simDR_left_bus_on_tr2,left_bus_on_tr2)
    right_bus_on_tr1 = smooth_light(simDR_right_bus_on_tr1,right_bus_on_tr1)
    pts250_n1 = smooth_light(simDR_pts250_n1,pts250_n1)
    pts250_n2 = smooth_light(simDR_pts250_n2,pts250_n2)
    vu_on_1 = smooth_light(simDR_vu_on_1,vu_on_1)
    turn_off_bat_1 = smooth_light(simDR_turn_off_bat_1,turn_off_bat_1)
    left_bus_use_bat = smooth_light(simDR_left_bus_use_bat,left_bus_use_bat)
    turn_off_bat_3 = smooth_light(simDR_turn_off_bat_3,turn_off_bat_3)
    vu_on_2 = smooth_light(simDR_vu_on_2,vu_on_2)
    turn_off_bat_2 = smooth_light(simDR_turn_off_bat_2,turn_off_bat_2)
    right_bus_use_bat = smooth_light(simDR_right_bus_use_bat,right_bus_use_bat)
    turn_off_bat_4 = smooth_light(simDR_turn_off_bat_4,turn_off_bat_4)
    bus_connected = smooth_light(simDR_bus_connected,bus_connected)
    emerg_inv_115 = smooth_light(simDR_emerg_inv_115,emerg_inv_115)
    bus_npk_1 = smooth_light(simDR_bus_npk_1,bus_npk_1)
    bus_npk_2 = smooth_light(simDR_bus_npk_2,bus_npk_2)
    apu_gen_on2 = smooth_light(simDR_apu_gen_on,apu_gen_on2)
    starter_high_rpm_1 = smooth_light(simDR_starter_high_rpm_1,starter_high_rpm_1)
    starter_high_rpm_2 = smooth_light(simDR_starter_high_rpm_2,starter_high_rpm_2)
    fuel_tank1_used = smooth_light(simDR_fuel_tank1_used,fuel_tank1_used)
    starter_high_rpm_3 = smooth_light(simDR_starter_high_rpm_3,starter_high_rpm_3)
    fuel_flow_auto_fail = smooth_light(simDR_fuel_flow_auto_fail,fuel_flow_auto_fail)
    fuel_cut_off_1 = smooth_light(simDR_fuel_cut_off_1,fuel_cut_off_1)
    fuel_cut_off_2 = smooth_light(simDR_fuel_cut_off_2,fuel_cut_off_2)
    fuel_cut_off_3 = smooth_light(simDR_fuel_cut_off_3,fuel_cut_off_3)
    fuel_level_automat = smooth_light(simDR_fuel_level_automat,fuel_level_automat)
    skv_overheat = smooth_light(simDR_skv_overheat,skv_overheat)
    eng_hydr_fail_1 = smooth_light(simDR_eng_hydr_fail_1,eng_hydr_fail_1)
    eng_hydr_fail_2 = smooth_light(simDR_eng_hydr_fail_2,eng_hydr_fail_2)
    eng_hydr_fail_3 = smooth_light(simDR_eng_hydr_fail_3,eng_hydr_fail_3)
    eng_hydr_fail_4 = smooth_light(simDR_eng_hydr_fail_4,eng_hydr_fail_4)
    skv_overpress_left = smooth_light(simDR_skv_overpress_left,skv_overpress_left)
    skv_overpress_right = smooth_light(simDR_skv_overpress_right,skv_overpress_right)
    skv_bleed_fail_1 = smooth_light(simDR_skv_bleed_fail_1,skv_bleed_fail_1)
    skv_bleed_fail_2 = smooth_light(simDR_skv_bleed_fail_2,skv_bleed_fail_2)
    skv_bleed_fail_3 = smooth_light(simDR_skv_bleed_fail_3,skv_bleed_fail_3)
    skv_tail_temp = smooth_light(simDR_skv_tail_temp,skv_tail_temp)
    skv_bleed_closed_1 = smooth_light(simDR_skv_bleed_closed_1,skv_bleed_closed_1)
    skv_bleed_closed_2 = smooth_light(simDR_skv_bleed_closed_2,skv_bleed_closed_2)
    skv_bleed_closed_3 = smooth_light(simDR_skv_bleed_closed_3,skv_bleed_closed_3)
    apd_work_1 = smooth_light(simDR_apd_work_1,apd_work_1)
    apd_work_2 = smooth_light(simDR_apd_work_2,apd_work_2)
    apd_work_3 = smooth_light(simDR_apd_work_3,apd_work_3)
    close_toilet = smooth_light(simDR_close_toilet,close_toilet)
    srd_low_press = smooth_light(simDR_srd_low_press,srd_low_press)
    srd_overpress = smooth_light(simDR_srd_overpress,srd_overpress)
    soi_ice_detected = smooth_light(simDR_soi_ice_detected,soi_ice_detected)
    soi_work = smooth_light(simDR_soi_work,soi_work)
    tail_temp_high = smooth_light(simDR_tail_temp_high,tail_temp_high)
    lavatory_heat = smooth_light(simDR_lavatory_heat,lavatory_heat)
    galley_heat = smooth_light(simDR_galley_heat,galley_heat)
    turn_on_aux = smooth_light(simDR_turn_on_aux,turn_on_aux)
    tks_contr_fail = smooth_light(simDR_tks_contr_fail,tks_contr_fail)
    light_fuel_pump_1 = smooth_light(simDR_light_fuel_pump_1,light_fuel_pump_1)
    light_fuel_pump_2 = smooth_light(simDR_light_fuel_pump_2,light_fuel_pump_2)
    light_fuel_pump_3 = smooth_light(simDR_light_fuel_pump_3,light_fuel_pump_3)
    light_fuel_pump_4 = smooth_light(simDR_light_fuel_pump_4,light_fuel_pump_4)
    light_fuel_pump_10 = smooth_light(simDR_light_fuel_pump_10,light_fuel_pump_10)
    light_fuel_pump_11 = smooth_light(simDR_light_fuel_pump_11,light_fuel_pump_11)
    light_fuel_pump_left_5 = smooth_light(simDR_light_fuel_pump_left_5,light_fuel_pump_left_5)
    light_fuel_pump_left_6 = smooth_light(simDR_light_fuel_pump_left_6,light_fuel_pump_left_6)
    light_fuel_pump_left_7 = smooth_light(simDR_light_fuel_pump_left_7,light_fuel_pump_left_7)
    light_fuel_pump_left_8 = smooth_light(simDR_light_fuel_pump_left_8,light_fuel_pump_left_8)
    light_fuel_pump_left_9 = smooth_light(simDR_light_fuel_pump_left_9,light_fuel_pump_left_9)
    light_fuel_pump_right_5 = smooth_light(simDR_light_fuel_pump_right_5,light_fuel_pump_right_5)
    light_fuel_pump_right_6 = smooth_light(simDR_light_fuel_pump_right_6,light_fuel_pump_right_6)
    light_fuel_pump_right_7 = smooth_light(simDR_light_fuel_pump_right_7,light_fuel_pump_right_7)
    light_fuel_pump_right_8 = smooth_light(simDR_light_fuel_pump_right_8,light_fuel_pump_right_8)
    light_fuel_pump_right_9 = smooth_light(simDR_light_fuel_pump_right_9,light_fuel_pump_right_9) 
end

function new_lights2()
    if simDR_fire_place > 0 and simDR_fire_main_switch > 0 and simDR_bus27_volt > 5 and azs_fireext1 < 1 and azs_fireext2 < 1 then
        if simDR_fire_eng_1 > 0 then
            fire_switch_loc = 1
            simDR_fire = 1
        elseif simDR_fire_eng_2 > 0 then
            fire_switch_loc = 1
            simDR_fire = 1
        elseif simDR_fire_eng_3 > 0 then
            fire_switch_loc = 1
            simDR_fire = 1
        elseif simDR_fire_apu > 0 then
            fire_switch_loc = 1
            simDR_fire = 1
        end
    elseif simDR_fire_main_switch > 0 and simDR_bus27_volt > 5 then
        if simDR_smoke_1 > 0 then
          if simDR_smoke_1_but < 1 then
            fire_switch_loc = 1
            simDR_fire = 1
          end
        elseif simDR_smoke_2 > 0 then
          if simDR_smoke_2_but < 1 then
            fire_switch_loc = 1
            simDR_fire = 1
          end
        elseif simDR_lamp_test_fire > 0 then
            fire_switch_loc = 1
        else
            fire_switch_loc = 0
        end
    elseif simDR_lamp_test_fire > 0 and simDR_bus27_volt > 5 then
        fire_switch_loc = 1
    else
        fire_switch_loc = 0
    end
end

function new_lights3()
    
    if simDR_lamp_test_eng > 0 then
        fuel_2500 = smooth_light(simDR_fuel_2500,fuel_2500)
    else
        fuel_2500 = smooth_light(simDR_ofuel_less_2500,fuel_2500)
    end
end


function after_physics()
    new_lights()
    --new_lights2()
    new_lights3()
end
