name: Feature Request
description: Suggest a new feature or improvement
labels: ["Type: Enhancement"]
body:
  - type: input
    id: title
    attributes:
      label: Feature Summary
      description: A brief description of the feature
      placeholder: "e.g., Add a route helper/vitual navigator for NVU"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: System / Area
      description: Which part of the aircraft would this affect?
      options:
        - Engines
        - Fuel System
        - Electrical
        - Hydraulics
        - Flight Controls
        - APU
        - Fire System
        - ABSU (Autopilot)
        - NVU and DISS (Doppler Navigation)
        - SVS (CADC, Central Air Data Computer)
        - TKS (Gyrocompass and Heading Reference System)
        - RSBN
        - Radar
        - Radio
        - TCAS
        - TAWS
        - KLN90B GPS
        - Transas TSS GPS
        - Kontur MFD
        - EFB Tablet
        - Cockpit
        - Exterior Model
        - Sounds
        - Flight Model
        - Liveries
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see
      placeholder: "I would like to see a route helper/virtual navigator for NVU integrated into Flight Planner that will automatically enter leg coordinates when needed like CIVA Helper"
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Why would this feature be useful? How would you use it?
      placeholder: "This would reduce the workload of the pilot by automating the entry of leg coordinates, allowing them to focus on other tasks."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: "Screenshots, links, diagrams..."
    validations:
      required: false
